/**
Copyright (c) 2025 Stappler Team <admin@stappler.org>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef CORE_RUNTIME_INCLUDE_LIBC_FLOAT_H_
#define CORE_RUNTIME_INCLUDE_LIBC_FLOAT_H_

#if defined(__SPRT_BUILD) && __STDC_HOSTED__ == 1

#include_next <float.h>

#else

#include <sprt/c/__sprt_float.h>

#ifndef FP_NAN
#define FP_NAN __SPRT_FP_NAN
#define FP_INFINITE __SPRT_FP_INFINITE
#define FP_ZERO __SPRT_FP_ZERO
#define FP_SUBNORMAL __SPRT_FP_SUBNORMAL
#define FP_NORMAL __SPRT_FP_NORMAL
#endif

#define LDBL_DECIMAL_DIG __SPRT_LDBL_DECIMAL_DIG
#define LDBL_DENORM_MIN __SPRT_LDBL_DENORM_MIN
#define LDBL_DIG __SPRT_LDBL_DIG
#define LDBL_EPSILON __SPRT_LDBL_EPSILON
#define LDBL_HAS_DENORM __SPRT_LDBL_HAS_DENORM
#define LDBL_HAS_SUBNORM __SPRT_LDBL_HAS_SUBNORM
#define LDBL_HAS_INFINITY __SPRT_LDBL_HAS_INFINITY
#define LDBL_HAS_QUIET_NAN __SPRT_LDBL_HAS_QUIET_NAN
#define LDBL_MANT_DIG __SPRT_LDBL_MANT_DIG
#define LDBL_MAX_10_EXP __SPRT_LDBL_MAX_10_EXP
#define LDBL_MAX_EXP __SPRT_LDBL_MAX_EXP
#define LDBL_MAX __SPRT_LDBL_MAX
#define LDBL_MIN_10_EXP __SPRT_LDBL_MIN_10_EXP
#define LDBL_MIN_EXP __SPRT_LDBL_MIN_EXP
#define LDBL_MIN __SPRT_LDBL_MIN
#define LDBL_NORM_MAX __SPRT_LDBL_NORM_MAX
#define LDBL_TRUE_MIN __SPRT_LDBL_TRUE_MIN

#define DBL_DECIMAL_DIG __SPRT_DBL_DECIMAL_DIG
#define DBL_DENORM_MIN __SPRT_DBL_DENORM_MIN
#define DBL_DIG __SPRT_DBL_DIG
#define DBL_EPSILON __SPRT_DBL_EPSILON
#define DBL_HAS_DENORM __SPRT_DBL_HAS_DENORM
#define DBL_HAS_SUBNORM __SPRT_DBL_HAS_SUBNORM
#define DBL_HAS_INFINITY __SPRT_DBL_HAS_INFINITY
#define DBL_HAS_QUIET_NAN __SPRT_DBL_HAS_QUIET_NAN
#define DBL_MANT_DIG __SPRT_DBL_MANT_DIG
#define DBL_MAX_10_EXP __SPRT_DBL_MAX_10_EXP
#define DBL_MAX_EXP __SPRT_DBL_MAX_EXP
#define DBL_MAX __SPRT_DBL_MAX
#define DBL_MIN_10_EXP __SPRT_DBL_MIN_10_EXP
#define DBL_MIN_EXP __SPRT_DBL_MIN_EXP
#define DBL_MIN __SPRT_DBL_MIN
#define DBL_NORM_MAX __SPRT_DBL_NORM_MAX
#define DBL_TRUE_MIN __SPRT_DBL_TRUE_MIN

#define FLT_DECIMAL_DIG __SPRT_FLT_DECIMAL_DIG
#define FLT_DENORM_MIN __SPRT_FLT_DENORM_MIN
#define FLT_DIG __SPRT_FLT_DIG
#define FLT_EPSILON __SPRT_FLT_EPSILON
#define FLT_HAS_DENORM __SPRT_FLT_HAS_DENORM
#define FLT_HAS_SUBNORM __SPRT_FLT_HAS_SUBNORM
#define FLT_HAS_INFINITY __SPRT_FLT_HAS_INFINITY
#define FLT_HAS_QUIET_NAN __SPRT_FLT_HAS_QUIET_NAN
#define FLT_MANT_DIG __SPRT_FLT_MANT_DIG
#define FLT_MAX_10_EXP __SPRT_FLT_MAX_10_EXP
#define FLT_MAX_EXP __SPRT_FLT_MAX_EXP
#define FLT_MAX __SPRT_FLT_MAX
#define FLT_MIN_10_EXP __SPRT_FLT_MIN_10_EXP
#define FLT_MIN_EXP __SPRT_FLT_MIN_EXP
#define FLT_MIN __SPRT_FLT_MIN
#define FLT_NORM_MAX __SPRT_FLT_NORM_MAX
#define FLT_TRUE_MIN __SPRT_FLT_TRUE_MIN

#endif

#endif // CORE_RUNTIME_INCLUDE_LIBC_FLOAT_H_
