## -*- mode: perl; -*-
#
# XWin cross-compilation target
# It's names as mingw because of some stupid build.info scripts, that checks the name instead of config itself

my %targets = (
    "mingw-xwin-clang-x64" => {
        inherit_from     => [ 'BASE_unix' ],
        CC               => "clang",
        cflags           => picker(default => "-m64 --target=x86_64-windows-msvc -Xclang -fms-volatile -D__STDC_NO_ATOMICS__ -Wall -Wno-incompatible-pointer-types -Wno-unused-function",
                                   debug   => "-g -O0",
                                   release => "-O3"),
        cppflags         => "-DUNICODE -D_UNICODE",
        sys_id           => "MINGW64",
        lib_cppflags     => "-DL_ENDIAN",
        ex_libs          => add(""),
        thread_scheme    => "winthreads",
        dso_scheme       => "win32",
        shared_target    => "mingw-shared",
        shared_cppflags  => add("_WINDLL"),
        shared_ldflag    => "",
        shared_rcflag    => "",
        perlasm_scheme   => "mingw64",
        perl_platform    => 'mingw',
        bn_ops           => add("SIXTY_FOUR_BIT"),
        asm_arch         => 'x86_64',
        uplink_arch      => 'x86_64',
        multilib         => "",
    },
)
