#include "../include/defs.h"

#define M_PI_2 __SPRT_M_PI_2

#if __SPRT_ARCH_ID == __SPRT_ARCH_ID_X86_64
#include "../musl-libc/src/math/x86_64/fabsf.c"
#include "../musl-libc/src/math/x86_64/fmaf.c"
#include "../musl-libc/src/math/x86_64/llrintf.c"
#include "../musl-libc/src/math/x86_64/lrintf.c"
#else
#include "../musl-libc/src/math/fabsf.c"
#include "../musl-libc/src/math/fmaf.c"
#include "../musl-libc/src/math/llrintf.c"
#include "../musl-libc/src/math/lrintf.c"
#endif

#include "../musl-libc/src/math/acoshf.c"
#include "../musl-libc/src/math/asinf.c"
#include "../musl-libc/src/math/asinhf.c"
#include "../musl-libc/src/math/atan2f.c"
#include "../musl-libc/src/math/atanf.c"
#include "../musl-libc/src/math/atanhf.c"
#include "../musl-libc/src/math/cbrtf.c"
#include "../musl-libc/src/math/ceilf.c"
#include "../musl-libc/src/math/copysignf.c"
#include "../musl-libc/src/math/__cosdf.c"
#include "../musl-libc/src/math/cosf.c"
#include "../musl-libc/src/math/coshf.c"
#include "../musl-libc/src/math/erff.c"
#include "../musl-libc/src/math/exp10f.c"
#include "../musl-libc/src/math/exp2f.c"
#include "../musl-libc/src/math/exp2f_data.c"
#include "../musl-libc/src/math/expm1f.c"
#include "../musl-libc/src/math/__expo2f.c"
#include "../musl-libc/src/math/fdimf.c"
#include "../musl-libc/src/math/finitef.c"
#include "../musl-libc/src/math/fmaxf.c"
#include "../musl-libc/src/math/fminf.c"
#include "../musl-libc/src/math/fmodf.c"
#include "../musl-libc/src/math/__fpclassifyf.c"
#include "../musl-libc/src/math/frexpf.c"
#include "../musl-libc/src/math/hypotf.c"
#include "../musl-libc/src/math/ilogbf.c"
#include "../musl-libc/src/math/ldexpf.c"
#include "../musl-libc/src/math/llroundf.c"
#include "../musl-libc/src/math/log10f.c"
#include "../musl-libc/src/math/logbf.c"
#include "../musl-libc/src/math/lroundf.c"
