#include "../include/defs.h"

#include "../musl-libc/src/math/log.c"
#include "../musl-libc/src/math/log_data.c"
#include "../musl-libc/src/math/__math_divzero.c"
#include "../musl-libc/src/math/__math_invalid.c"
#include "../musl-libc/src/math/__math_oflow.c"
#include "../musl-libc/src/math/__math_uflow.c"
#include "../musl-libc/src/math/__math_xflow.c"
#include "../musl-libc/src/math/modf.c"
#include "../musl-libc/src/math/nan.c"
#include "../musl-libc/src/math/nearbyint.c"
#include "../musl-libc/src/math/nextafter.c"
#include "../musl-libc/src/math/nexttoward.c"
#include "../musl-libc/src/math/remainder.c"
#include "../musl-libc/src/math/__rem_pio2.c"
#include "../musl-libc/src/math/__rem_pio2_large.c"
#include "../musl-libc/src/math/remquo.c"
