#include "../include/defs.h"

#define M_PI_4 __SPRT_M_PI_4

#if __SPRT_ARCH_ID == __SPRT_ARCH_ID_X86_64
#include "../musl-libc/src/math/x86_64/fabsl.c"
#include "../musl-libc/src/math/x86_64/fmodl.c"
#include "../musl-libc/src/math/x86_64/llrintl.c"
#include "../musl-libc/src/math/x86_64/lrintl.c"
#else
#include "../musl-libc/src/math/acosl.c"
#include "../musl-libc/src/math/asinl.c"
#include "../musl-libc/src/math/atan2l.c"
#include "../musl-libc/src/math/atanl.c"
#include "../musl-libc/src/math/exp2l.c"
#include "../musl-libc/src/math/expl.c"
#include "../musl-libc/src/math/ceill.c"
#include "../musl-libc/src/math/fabsl.c"
#include "../musl-libc/src/math/fmodl.c"
#include "../musl-libc/src/math/llrintl.c"
#include "../musl-libc/src/math/lrintl.c"
#endif

#include "../musl-libc/src/math/acoshl.c"
#include "../musl-libc/src/math/asinhl.c"
#include "../musl-libc/src/math/atanhl.c"
#include "../musl-libc/src/math/cbrtl.c"
#include "../musl-libc/src/math/copysignl.c"
#include "../musl-libc/src/math/coshl.c"
#include "../musl-libc/src/math/__cosl.c"
#include "../musl-libc/src/math/cosl.c"
#include "../musl-libc/src/math/erfl.c"
#include "../musl-libc/src/math/exp10l.c"
#include "../musl-libc/src/math/fdiml.c"
#include "../musl-libc/src/math/fmal.c"
#include "../musl-libc/src/math/fmaxl.c"
#include "../musl-libc/src/math/fminl.c"
#include "../musl-libc/src/math/__fpclassifyl.c"
#include "../musl-libc/src/math/frexpl.c"
#include "../musl-libc/src/math/ilogbl.c"
#include "../musl-libc/src/math/__invtrigl.c"
#include "../musl-libc/src/math/ldexpl.c"
#include "../musl-libc/src/math/lgammal.c"
#include "../musl-libc/src/math/llroundl.c"
#include "../musl-libc/src/math/logbl.c"
#include "../musl-libc/src/math/lroundl.c"
