#include "../include/defs.h"

#if __SPRT_ARCH_ID == __SPRT_ARCH_ID_X86_64
#include "../musl-libc/src/math/x86_64/fabs.c"
#include "../musl-libc/src/math/x86_64/fma.c"
#include "../musl-libc/src/math/x86_64/llrint.c"
#include "../musl-libc/src/math/x86_64/lrint.c"
#else
#include "../musl-libc/src/math/fabs.c"
#include "../musl-libc/src/math/fma.c"
#include "../musl-libc/src/math/llrint.c"
#include "../musl-libc/src/math/lrint.c"
#endif

#include "../musl-libc/src/math/acosh.c"
#include "../musl-libc/src/math/asin.c"
#include "../musl-libc/src/math/asinh.c"
#include "../musl-libc/src/math/atan2.c"
#include "../musl-libc/src/math/atan.c"
#include "../musl-libc/src/math/atanh.c"
#include "../musl-libc/src/math/cbrt.c"
#include "../musl-libc/src/math/ceil.c"
#include "../musl-libc/src/math/copysign.c"
#include "../musl-libc/src/math/__cos.c"
#include "../musl-libc/src/math/cos.c"
#include "../musl-libc/src/math/cosh.c"
#include "../musl-libc/src/math/erf.c"
#include "../musl-libc/src/math/exp10.c"
#include "../musl-libc/src/math/exp2.c"
#include "../musl-libc/src/math/expm1.c"
#include "../musl-libc/src/math/__expo2.c"
#include "../musl-libc/src/math/fdim.c"
#include "../musl-libc/src/math/finite.c"
#include "../musl-libc/src/math/fmax.c"
#include "../musl-libc/src/math/fmin.c"
#include "../musl-libc/src/math/fmod.c"
#include "../musl-libc/src/math/__fpclassify.c"
#include "../musl-libc/src/math/frexp.c"
#include "../musl-libc/src/math/hypot.c"
#include "../musl-libc/src/math/ilogb.c"
#include "../musl-libc/src/math/ldexp.c"
#include "../musl-libc/src/math/lgamma.c"
#include "../musl-libc/src/math/llround.c"
#include "../musl-libc/src/math/log10.c"
#include "../musl-libc/src/math/logb.c"
#include "../musl-libc/src/math/lround.c"
