#include "../include/defs.h"

#include "../musl-libc/src/math/logf.c"
#include "../musl-libc/src/math/logf_data.c"
#include "../musl-libc/src/math/__math_divzerof.c"
#include "../musl-libc/src/math/__math_invalidf.c"
#include "../musl-libc/src/math/__math_oflowf.c"
#include "../musl-libc/src/math/__math_uflowf.c"
#include "../musl-libc/src/math/__math_xflowf.c"
#include "../musl-libc/src/math/modff.c"
#include "../musl-libc/src/math/nanf.c"
#include "../musl-libc/src/math/nearbyintf.c"
#include "../musl-libc/src/math/nextafterf.c"
#include "../musl-libc/src/math/nexttowardf.c"
#include "../musl-libc/src/math/remainderf.c"
#include "../musl-libc/src/math/__rem_pio2f.c"
#include "../musl-libc/src/math/remquof.c"
