set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSROOT )
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_C_FLAGS_INIT "  ")
set(CMAKE_CXX_FLAGS_INIT "")
set(CMAKE_C_COMPILER "C:/LLVM/bin/clang-cl.exe")
set(CMAKE_CXX_COMPILER "C:/LLVM/bin/clang-cl.exe")
set(CMAKE_RC_COMPILER "C:/LLVM/bin/llvm-rc.exe")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-Lc:/msys64/home/sbkarr/xenolith-engine/runtime/toolchains/toolchain-windows/sysroot-windows/lib ")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-Lc:/msys64/home/sbkarr/xenolith-engine/runtime/toolchains/toolchain-windows/sysroot-windows/lib ")
set(CMAKE_VERBOSE_MAKEFILE ON)
set(CMAKE_LINKER_TYPE LLD)
