/**
Copyright (c) 2025 Stappler Team <admin@stappler.org>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef CORE_RUNTIME_INCLUDE_C_CROSS___SPRT_CONFIG_H_
#define CORE_RUNTIME_INCLUDE_C_CROSS___SPRT_CONFIG_H_

// Per-OS/Per-arch Stappler Runtime configuration
#include <sprt/c/bits/__sprt_def.h>

#define SPRT_CROSS_CONFIG_NAME_(x) #x
#define SPRT_CROSS_CONFIG_NAME(x) SPRT_CROSS_CONFIG_NAME_(x)

// clang-format off
#include SPRT_CROSS_CONFIG_NAME(sprt/c/cross/__SPRT_PLATFORM_NAME/config.h)
#include SPRT_CROSS_CONFIG_NAME(sprt/c/cross/__SPRT_PLATFORM_NAME/__SPRT_ARCH_NAME/config.h)
// clang-format on

#if __SPRT_HAS_ATTR(warning)
#define __SPRT_CONFIG_UNAVAILABLE_NOTICE(Value) \
	__attribute__((warning("This function is not available on current OS/Arch and will be noop (" #Value ")")))
#else
#define __SPRT_CONFIG_UNAVAILABLE_NOTICE(Value)
#endif

/*
	All fallback values should be defined there
	Use this list to create your own platform configurations
*/

#ifndef __SPRT_CONFIG_HAVE_UNISTD_CHOWN
#define __SPRT_CONFIG_HAVE_UNISTD_CHOWN 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_CHOWN == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_CHOWN_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_CHOWN)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_CHOWN_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_DUP
#define __SPRT_CONFIG_HAVE_UNISTD_DUP 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_DUP == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_DUP_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_DUP)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_DUP_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_DUP3
#define __SPRT_CONFIG_HAVE_UNISTD_DUP3 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_DUP3 == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_DUP3_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_DUP3)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_DUP3_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_EXEC
#define __SPRT_CONFIG_HAVE_UNISTD_EXEC 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_EXEC == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_EXEC_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_EXEC)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_EXEC_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_FEXEC
#define __SPRT_CONFIG_HAVE_UNISTD_FEXEC 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_FEXEC == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_FEXEC_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_FEXEC)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_FEXEC_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN
#define __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_SETLOGIN)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME
#define __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_NICE
#define __SPRT_CONFIG_HAVE_UNISTD_NICE 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_NICE == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_NICE_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_NICE)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_NICE_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_GETPPID
#define __SPRT_CONFIG_HAVE_UNISTD_GETPPID 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_GETPPID == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_GETPPID_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_GETPPID)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_GETPPID_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_SETUIDGID
#define __SPRT_CONFIG_HAVE_UNISTD_SETUIDGID 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_SETUIDGID == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_SETUIDGID_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_SETUIDGID)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_SETUIDGID_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_FORK
#define __SPRT_CONFIG_HAVE_UNISTD_FORK 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_FORK == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_FORK_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_FORK)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_FORK_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_SETHOSTNAME
#define __SPRT_CONFIG_HAVE_UNISTD_SETHOSTNAME 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_SETHOSTNAME == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_SETHOSTNAME_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_SETHOSTNAME)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_SETHOSTNAME_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_UNISTD_BRK
#define __SPRT_CONFIG_HAVE_UNISTD_BRK 1
#endif

#if __SPRT_CONFIG_HAVE_UNISTD_BRK == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_UNISTD_BRK_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_UNISTD_BRK)
#else
#define __SPRT_CONFIG_HAVE_UNISTD_BRK_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_SELECT
#define __SPRT_CONFIG_HAVE_SELECT 1
#endif

#if __SPRT_CONFIG_HAVE_SELECT == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_SELECT_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_SELECT)
#else
#define __SPRT_CONFIG_HAVE_SELECT_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_TIME_ADJTIME
#define __SPRT_CONFIG_HAVE_TIME_ADJTIME 1
#endif

#if __SPRT_CONFIG_HAVE_TIME_ADJTIME == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_TIME_ADJTIME_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_TIME_ADJTIME)
#else
#define __SPRT_CONFIG_HAVE_TIME_ADJTIME_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_EPOLL
#define __SPRT_CONFIG_HAVE_EPOLL 0
#endif

#if __SPRT_CONFIG_HAVE_EPOLL == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_EPOLL_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_EPOLL)
#else
#define __SPRT_CONFIG_HAVE_EPOLL_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_EVENTFD
#define __SPRT_CONFIG_HAVE_EVENTFD 0
#endif

#if __SPRT_CONFIG_HAVE_EVENTFD == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_EVENTFD_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_EVENTFD)
#else
#define __SPRT_CONFIG_HAVE_EVENTFD_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_SIGNALFD
#define __SPRT_CONFIG_HAVE_SIGNALFD 0
#endif

#if __SPRT_CONFIG_HAVE_SIGNALFD == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_SIGNALFD_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_SIGNALFD)
#else
#define __SPRT_CONFIG_HAVE_SIGNALFD_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_TIMERFD
#define __SPRT_CONFIG_HAVE_TIMERFD 0
#endif

#if __SPRT_CONFIG_HAVE_TIMERFD == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_TIMERFD_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_TIMERFD)
#else
#define __SPRT_CONFIG_HAVE_TIMERFD_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_ALOOPER
#define __SPRT_CONFIG_HAVE_ALOOPER 0
#endif

#if __SPRT_CONFIG_HAVE_ALOOPER == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_ALOOPER_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_ALOOPER)
#else
#define __SPRT_CONFIG_HAVE_ALOOPER_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_URING
#define __SPRT_CONFIG_HAVE_URING 0
#endif

#if __SPRT_CONFIG_HAVE_URING == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_URING_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_URING)
#else
#define __SPRT_CONFIG_HAVE_URING_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FUTEX
#define __SPRT_CONFIG_HAVE_FUTEX 0
#endif

#if __SPRT_CONFIG_HAVE_FUTEX == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FUTEX_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FUTEX)
#else
#define __SPRT_CONFIG_HAVE_FUTEX_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_STDLIB_MB
#define __SPRT_CONFIG_HAVE_STDLIB_MB 0
#endif

#if __SPRT_CONFIG_HAVE_STDLIB_MB == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_STDLIB_MB_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_STDLIB_MB)
#else
#define __SPRT_CONFIG_HAVE_STDLIB_MB_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_STDIO_OPEN_MEMSTREAM
#define __SPRT_CONFIG_HAVE_STDIO_OPEN_MEMSTREAM 1
#endif

#if __SPRT_CONFIG_HAVE_STDIO_OPEN_MEMSTREAM == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_STDIO_OPEN_MEMSTREAM_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_STDIO_OPEN_MEMSTREAM)
#else
#define __SPRT_CONFIG_HAVE_STDIO_OPEN_MEMSTREAM_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_CANCEL
#define __SPRT_CONFIG_HAVE_PTHREAD_CANCEL 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_CANCEL == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_CANCEL_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_CANCEL)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_CANCEL_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED
#define __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY
#define __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_AFFINITY)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT
#define __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY
#define __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN
#define __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN
#define __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_PTHREAD_GETNAME
#define __SPRT_CONFIG_HAVE_PTHREAD_GETNAME 1
#endif

#if __SPRT_CONFIG_HAVE_PTHREAD_GETNAME == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_PTHREAD_GETNAME_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_PTHREAD_GETNAME)
#else
#define __SPRT_CONFIG_HAVE_PTHREAD_GETNAME_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_LOCALE_EXT
#define __SPRT_CONFIG_HAVE_LOCALE_EXT 1
#endif

#if __SPRT_CONFIG_HAVE_LOCALE_EXT == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_LOCALE_EXT_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_LOCALE_EXT)
#else
#define __SPRT_CONFIG_HAVE_LOCALE_EXT_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_SIGNAL_SIGPROCMASK
#define __SPRT_CONFIG_HAVE_SIGNAL_SIGPROCMASK 1
#endif

#if __SPRT_CONFIG_HAVE_SIGNAL_SIGPROCMASK == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_SIGNAL_SIGPROCMASK_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_SIGNAL_SIGPROCMASK)
#else
#define __SPRT_CONFIG_HAVE_SIGNAL_SIGPROCMASK_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_NLTYPES_CAT
#define __SPRT_CONFIG_HAVE_NLTYPES_CAT 1
#endif

#if __SPRT_CONFIG_HAVE_NLTYPES_CAT == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_NLTYPES_CAT_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_NLTYPES_CAT)
#else
#define __SPRT_CONFIG_HAVE_NLTYPES_CAT_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FCNTL_SPLICE
#define __SPRT_CONFIG_HAVE_FCNTL_SPLICE 1
#endif

#if __SPRT_CONFIG_HAVE_FCNTL_SPLICE == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FCNTL_SPLICE_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FCNTL_SPLICE)
#else
#define __SPRT_CONFIG_HAVE_FCNTL_SPLICE_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FCNTL_TEE
#define __SPRT_CONFIG_HAVE_FCNTL_TEE 1
#endif

#if __SPRT_CONFIG_HAVE_FCNTL_TEE == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FCNTL_TEE_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FCNTL_TEE)
#else
#define __SPRT_CONFIG_HAVE_FCNTL_TEE_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FCNTL_FALLOCATE
#define __SPRT_CONFIG_HAVE_FCNTL_FALLOCATE 1
#endif

#if __SPRT_CONFIG_HAVE_FCNTL_FALLOCATE == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FCNTL_FALLOCATE_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FCNTL_FALLOCATE)
#else
#define __SPRT_CONFIG_HAVE_FCNTL_FALLOCATE_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FCNTL_FADVICE
#define __SPRT_CONFIG_HAVE_FCNTL_FADVICE 1
#endif

#if __SPRT_CONFIG_HAVE_FCNTL_FADVICE == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FCNTL_FADVICE_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FCNTL_FADVICE)
#else
#define __SPRT_CONFIG_HAVE_FCNTL_FADVICE_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FCNTL_READAHEAD
#define __SPRT_CONFIG_HAVE_FCNTL_READAHEAD 1
#endif

#if __SPRT_CONFIG_HAVE_FCNTL_READAHEAD == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FCNTL_READAHEAD_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FCNTL_READAHEAD)
#else
#define __SPRT_CONFIG_HAVE_FCNTL_READAHEAD_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_FCNTL_SYNC_FILE_RANGE
#define __SPRT_CONFIG_HAVE_FCNTL_SYNC_FILE_RANGE 1
#endif

#if __SPRT_CONFIG_HAVE_FCNTL_SYNC_FILE_RANGE == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_FCNTL_SYNC_FILE_RANGE_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_FCNTL_SYNC_FILE_RANGE)
#else
#define __SPRT_CONFIG_HAVE_FCNTL_SYNC_FILE_RANGE_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_TIME_CLOCK_SETTIME
#define __SPRT_CONFIG_HAVE_TIME_CLOCK_SETTIME 1
#endif

#if __SPRT_CONFIG_HAVE_TIME_CLOCK_SETTIME == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_TIME_CLOCK_SETTIME_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_TIME_CLOCK_SETTIME)
#else
#define __SPRT_CONFIG_HAVE_TIME_CLOCK_SETTIME_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_MMAN_MLOCKALL
#define __SPRT_CONFIG_HAVE_MMAN_MLOCKALL 1
#endif

#if __SPRT_CONFIG_HAVE_MMAN_MLOCKALL == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_MMAN_MLOCKALL_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_MMAN_MLOCKALL)
#else
#define __SPRT_CONFIG_HAVE_MMAN_MLOCKALL_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_MMAN_MREMAP
#define __SPRT_CONFIG_HAVE_MMAN_MREMAP 1
#endif

#if __SPRT_CONFIG_HAVE_MMAN_MREMAP == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_MMAN_MREMAP_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_MMAN_MREMAP)
#else
#define __SPRT_CONFIG_HAVE_MMAN_MREMAP_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_MMAN_MEMFD
#define __SPRT_CONFIG_HAVE_MMAN_MEMFD 1
#endif

#if __SPRT_CONFIG_HAVE_MMAN_MEMFD == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_MMAN_MEMFD_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_MMAN_MEMFD)
#else
#define __SPRT_CONFIG_HAVE_MMAN_MEMFD_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_STAT_MKFIFO
#define __SPRT_CONFIG_HAVE_STAT_MKFIFO 1
#endif

#if __SPRT_CONFIG_HAVE_STAT_MKFIFO == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_STAT_MKFIFO_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_STAT_MKFIFO)
#else
#define __SPRT_CONFIG_HAVE_STAT_MKFIFO_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_STAT_MKNOD
#define __SPRT_CONFIG_HAVE_STAT_MKNOD 1
#endif

#if __SPRT_CONFIG_HAVE_STAT_MKNOD == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_STAT_MKNOD_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_STAT_MKNOD)
#else
#define __SPRT_CONFIG_HAVE_STAT_MKNOD_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_TIME_TIMEOFDAY
#define __SPRT_CONFIG_HAVE_TIME_TIMEOFDAY 1
#endif

#if __SPRT_CONFIG_HAVE_TIME_TIMEOFDAY == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_TIME_TIMEOFDAY_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_TIME_TIMEOFDAY)
#else
#define __SPRT_CONFIG_HAVE_TIME_TIMEOFDAY_NOTICE
#endif


#ifndef __SPRT_CONFIG_HAVE_TIME_TIMER
#define __SPRT_CONFIG_HAVE_TIME_TIMER 1
#endif

#if __SPRT_CONFIG_HAVE_TIME_TIMER == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_TIME_TIMER_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_TIME_TIMER)
#else
#define __SPRT_CONFIG_HAVE_TIME_TIMER_NOTICE
#endif

#ifndef __SPRT_CONFIG_HAVE_WINAPI
#define __SPRT_CONFIG_HAVE_WINAPI 0
#endif

#if __SPRT_CONFIG_HAVE_WINAPI == 0 && __SPRT_CONFIG_DEFINE_UNAVAILABLE_FUNCTIONS
#define __SPRT_CONFIG_HAVE_WINAPI_NOTICE __SPRT_CONFIG_UNAVAILABLE_NOTICE(__SPRT_CONFIG_HAVE_WINAPI)
#else
#define __SPRT_CONFIG_HAVE_WINAPI_NOTICE
#endif

#endif
