#include "../include/defs.h"

#if !SPRT_WINDOWS
#include "../../musl-libc/src/string/strlen.c"
#include "../../musl-libc/src/string/wcscasecmp_l.c"
#include "../../musl-libc/src/string/wcsncasecmp_l.c"
#include "../../musl-libc/src/string/wcscasecmp.c"
#include "../../musl-libc/src/string/wcsncasecmp.c"
#include "../../musl-libc/src/string/wcscmp.c"
#include "../../musl-libc/src/string/wcsncmp.c"
#include "../../musl-libc/src/string/wcsnlen.c"
#include "../../musl-libc/src/string/wcscpy.c"
#include "../../musl-libc/src/string/wcslen.c"
#include "../../musl-libc/src/string/wcsncpy.c"
#include "../../musl-libc/src/string/wcsstr.c"
#endif

#include "../../musl-libc/src/string/stpcpy.c"
#include "../../musl-libc/src/string/strchrnul.c"

#include "../../musl-libc/src/string/swab.c"
#include "../../musl-libc/src/string/wcpcpy.c"
#include "../../musl-libc/src/string/wcpncpy.c"
#include "../../musl-libc/src/string/wcscat.c"
#include "../../musl-libc/src/string/wcschr.c"
#include "../../musl-libc/src/string/wcscspn.c"
#include "../../musl-libc/src/string/wcsdup.c"
#include "../../musl-libc/src/string/wcsncat.c"
#include "../../musl-libc/src/string/wcspbrk.c"
#include "../../musl-libc/src/string/wcsrchr.c"
#include "../../musl-libc/src/string/wcsspn.c"
#include "../../musl-libc/src/string/wcstok.c"
#include "../../musl-libc/src/string/wcswcs.c"
#include "../../musl-libc/src/string/wmemchr.c"
#include "../../musl-libc/src/string/wmemcmp.c"
#include "../../musl-libc/src/string/wmemcpy.c"
#include "../../musl-libc/src/string/wmemmove.c"
#include "../../musl-libc/src/string/wmemset.c"
