#define __SPRT_CONFIG_HAVE_ALLIGNED_ALLOC 0
#define __SPRT_CONFIG_HAVE_UNISTD_FEXEC 0
#define __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME 0
#define __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN 0
#define __SPRT_CONFIG_HAVE_ADJTIME 0

#ifndef __SPRT_CONFIG_HAVE_EPOLL
#define __SPRT_CONFIG_HAVE_EPOLL 1
#endif

#ifndef __SPRT_CONFIG_HAVE_EVENTFD
#define __SPRT_CONFIG_HAVE_EVENTFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_SIGNALFD
#define __SPRT_CONFIG_HAVE_SIGNALFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_TIMERFD
#define __SPRT_CONFIG_HAVE_TIMERFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_ALOOPER
#define __SPRT_CONFIG_HAVE_ALOOPER 1
#endif

#ifndef __SPRT_CONFIG_HAVE_URING
#define __SPRT_CONFIG_HAVE_URING 1
#endif

#ifndef __SPRT_CONFIG_HAVE_STDLIB_MB
#define __SPRT_CONFIG_HAVE_STDLIB_MB 1
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_CANCEL
#define __SPRT_CONFIG_HAVE_PTHREAD_CANCEL 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_ROBUST 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO
#define __SPRT_CONFIG_HAVE_PTHREAD_MUTEX_PRIO 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED
#define __SPRT_CONFIG_HAVE_PTHREAD_INHERITSCHED 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY
#define __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT
#define __SPRT_CONFIG_HAVE_PTHREAD_ATTRDEFAULT 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY
#define __SPRT_CONFIG_HAVE_PTHREAD_CONCURRENCY 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN
#define __SPRT_CONFIG_HAVE_PTHREAD_TRYJOIN 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN
#define __SPRT_CONFIG_HAVE_PTHREAD_TIMEDJOIN 0
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_GETNAME
#define __SPRT_CONFIG_HAVE_PTHREAD_GETNAME 0
#endif
