#define __SPRT_CONFIG_HAVE_UNISTD_FEXEC 0

#define __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME 0

#define __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN 0

#define __SPRT_CONFIG_HAVE_TIME_ADJTIME 0

#ifndef __SPRT_CONFIG_HAVE_EPOLL
#define __SPRT_CONFIG_HAVE_EPOLL 1
#endif

#ifndef __SPRT_CONFIG_HAVE_EVENTFD
#define __SPRT_CONFIG_HAVE_EVENTFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_SIGNALFD
#define __SPRT_CONFIG_HAVE_SIGNALFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_TIMERFD
#define __SPRT_CONFIG_HAVE_TIMERFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_ALOOPER
#define __SPRT_CONFIG_HAVE_ALOOPER 1
#endif

#ifndef __SPRT_CONFIG_HAVE_ALOG
#define __SPRT_CONFIG_HAVE_ALOG 1
#endif

#ifndef __SPRT_CONFIG_HAVE_URING
#define __SPRT_CONFIG_HAVE_URING 1
#endif

#ifndef __SPRT_CONFIG_HAVE_FUTEX
#define __SPRT_CONFIG_HAVE_FUTEX 1
#endif

#ifndef __SPRT_CONFIG_HAVE_STDLIB_MB
#define __SPRT_CONFIG_HAVE_STDLIB_MB 1
#endif

#ifndef __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY
#define __SPRT_CONFIG_HAVE_PTHREAD_AFFINITY 0
#endif
