#define __SPRT_CONFIG_HAVE_ALLIGNED_ALLOC 0
#define __SPRT_CONFIG_HAVE_UNISTD_FEXEC 0
#define __SPRT_CONFIG_HAVE_UNISTD_DOMAINNAME 0
#define __SPRT_CONFIG_HAVE_UNISTD_SETLOGIN 0
#define __SPRT_CONFIG_HAVE_ADJTIME 0

#ifndef __SPRT_CONFIG_HAVE_EPOLL
#define __SPRT_CONFIG_HAVE_EPOLL 1
#endif

#ifndef __SPRT_CONFIG_HAVE_EVENTFD
#define __SPRT_CONFIG_HAVE_EVENTFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_SIGNALFD
#define __SPRT_CONFIG_HAVE_SIGNALFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_TIMERFD
#define __SPRT_CONFIG_HAVE_TIMERFD 1
#endif

#ifndef __SPRT_CONFIG_HAVE_ALOOPER
#define __SPRT_CONFIG_HAVE_ALOOPER 1
#endif

#ifndef __SPRT_CONFIG_HAVE_URING
#define __SPRT_CONFIG_HAVE_URING 1
#endif
