/**
Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
**/

#ifndef SPRT_WRAPPERS_WINDOWS_ERRORS_H_
#define SPRT_WRAPPERS_WINDOWS_ERRORS_H_

// clang-format off

#define NO_ERROR 0L 

#define _HRESULT_TYPEDEF_(_sc) ((HRESULT)_sc)

#define ERROR_SUCCESS                    0L
#define ERROR_INVALID_FUNCTION           1L
#define ERROR_FILE_NOT_FOUND             2L
#define ERROR_PATH_NOT_FOUND             3L
#define ERROR_TOO_MANY_OPEN_FILES        4L
#define ERROR_ACCESS_DENIED              5L
#define ERROR_INVALID_HANDLE             6L
#define ERROR_ARENA_TRASHED              7L
#define ERROR_NOT_ENOUGH_MEMORY          8L
#define ERROR_INVALID_BLOCK              9L
#define ERROR_BAD_ENVIRONMENT            10L
#define ERROR_BAD_FORMAT                 11L
#define ERROR_INVALID_ACCESS             12L
#define ERROR_INVALID_DATA               13L
#define ERROR_OUTOFMEMORY                14L
#define ERROR_INVALID_DRIVE              15L
#define ERROR_CURRENT_DIRECTORY          16L
#define ERROR_NOT_SAME_DEVICE            17L
#define ERROR_NO_MORE_FILES              18L
#define ERROR_WRITE_PROTECT              19L
#define ERROR_BAD_UNIT                   20L
#define ERROR_NOT_READY                  21L
#define ERROR_BAD_COMMAND                22L
#define ERROR_CRC                        23L
#define ERROR_BAD_LENGTH                 24L
#define ERROR_SEEK                       25L
#define ERROR_NOT_DOS_DISK               26L
#define ERROR_SECTOR_NOT_FOUND           27L
#define ERROR_OUT_OF_PAPER               28L
#define ERROR_WRITE_FAULT                29L
#define ERROR_READ_FAULT                 30L
#define ERROR_GEN_FAILURE                31L
#define ERROR_SHARING_VIOLATION          32L
#define ERROR_LOCK_VIOLATION             33L
#define ERROR_WRONG_DISK                 34L
#define ERROR_SHARING_BUFFER_EXCEEDED    36L
#define ERROR_HANDLE_EOF                 38L
#define ERROR_HANDLE_DISK_FULL           39L
#define ERROR_NOT_SUPPORTED              50L
#define ERROR_REM_NOT_LIST               51L
#define ERROR_DUP_NAME                   52L
#define ERROR_BAD_NETPATH                53L
#define ERROR_NETWORK_BUSY               54L
#define ERROR_DEV_NOT_EXIST              55L
#define ERROR_TOO_MANY_CMDS              56L
#define ERROR_ADAP_HDW_ERR               57L
#define ERROR_BAD_NET_RESP               58L
#define ERROR_UNEXP_NET_ERR              59L
#define ERROR_BAD_REM_ADAP               60L
#define ERROR_PRINTQ_FULL                61L
#define ERROR_NO_SPOOL_SPACE             62L
#define ERROR_PRINT_CANCELLED            63L
#define ERROR_NETNAME_DELETED            64L
#define ERROR_NETWORK_ACCESS_DENIED      65L
#define ERROR_BAD_DEV_TYPE               66L
#define ERROR_BAD_NET_NAME               67L
#define ERROR_TOO_MANY_NAMES             68L
#define ERROR_TOO_MANY_SESS              69L
#define ERROR_SHARING_PAUSED             70L
#define ERROR_REQ_NOT_ACCEP              71L
#define ERROR_REDIR_PAUSED               72L
#define ERROR_FILE_EXISTS                80L
#define ERROR_CANNOT_MAKE                82L
#define ERROR_FAIL_I24                   83L
#define ERROR_OUT_OF_STRUCTURES          84L
#define ERROR_ALREADY_ASSIGNED           85L
#define ERROR_INVALID_PASSWORD           86L
#define ERROR_INVALID_PARAMETER          87L
#define ERROR_NET_WRITE_FAULT            88L
#define ERROR_NO_PROC_SLOTS              89L
#define ERROR_TOO_MANY_SEMAPHORES        100L
#define ERROR_EXCL_SEM_ALREADY_OWNED     101L
#define ERROR_SEM_IS_SET                 102L
#define ERROR_TOO_MANY_SEM_REQUESTS      103L
#define ERROR_INVALID_AT_INTERRUPT_TIME  104L
#define ERROR_SEM_OWNER_DIED             105L
#define ERROR_SEM_USER_LIMIT             106L
#define ERROR_DISK_CHANGE                107L
#define ERROR_DRIVE_LOCKED               108L
#define ERROR_BROKEN_PIPE                109L
#define ERROR_OPEN_FAILED                110L
#define ERROR_BUFFER_OVERFLOW            111L
#define ERROR_DISK_FULL                  112L
#define ERROR_NO_MORE_SEARCH_HANDLES     113L
#define ERROR_INVALID_TARGET_HANDLE      114L
#define ERROR_INVALID_CATEGORY           117L
#define ERROR_INVALID_VERIFY_SWITCH      118L
#define ERROR_BAD_DRIVER_LEVEL           119L
#define ERROR_CALL_NOT_IMPLEMENTED       120L
#define ERROR_SEM_TIMEOUT                121L
#define ERROR_INSUFFICIENT_BUFFER        122L
#define ERROR_INVALID_NAME               123L
#define ERROR_INVALID_LEVEL              124L
#define ERROR_NO_VOLUME_LABEL            125L
#define ERROR_MOD_NOT_FOUND              126L
#define ERROR_PROC_NOT_FOUND             127L
#define ERROR_WAIT_NO_CHILDREN           128L
#define ERROR_CHILD_NOT_COMPLETE         129L
#define ERROR_DIRECT_ACCESS_HANDLE       130L
#define ERROR_NEGATIVE_SEEK              131L
#define ERROR_SEEK_ON_DEVICE             132L
#define ERROR_IS_JOIN_TARGET             133L
#define ERROR_IS_JOINED                  134L
#define ERROR_IS_SUBSTED                 135L
#define ERROR_NOT_JOINED                 136L
#define ERROR_NOT_SUBSTED                137L
#define ERROR_JOIN_TO_JOIN               138L
#define ERROR_SUBST_TO_SUBST             139L
#define ERROR_JOIN_TO_SUBST              140L
#define ERROR_SUBST_TO_JOIN              141L
#define ERROR_BUSY_DRIVE                 142L
#define ERROR_SAME_DRIVE                 143L
#define ERROR_DIR_NOT_ROOT               144L
#define ERROR_DIR_NOT_EMPTY              145L
#define ERROR_IS_SUBST_PATH              146L
#define ERROR_IS_JOIN_PATH               147L
#define ERROR_PATH_BUSY                  148L
#define ERROR_IS_SUBST_TARGET            149L
#define ERROR_SYSTEM_TRACE               150L
#define ERROR_INVALID_EVENT_COUNT        151L
#define ERROR_TOO_MANY_MUXWAITERS        152L
#define ERROR_INVALID_LIST_FORMAT        153L
#define ERROR_LABEL_TOO_LONG             154L
#define ERROR_TOO_MANY_TCBS              155L
#define ERROR_SIGNAL_REFUSED             156L
#define ERROR_DISCARDED                  157L
#define ERROR_NOT_LOCKED                 158L
#define ERROR_BAD_THREADID_ADDR          159L
#define ERROR_BAD_ARGUMENTS              160L
#define ERROR_BAD_PATHNAME               161L
#define ERROR_SIGNAL_PENDING             162L
#define ERROR_MAX_THRDS_REACHED          164L
#define ERROR_LOCK_FAILED                167L
#define ERROR_BUSY                       170L
#define ERROR_DEVICE_SUPPORT_IN_PROGRESS 171L
#define ERROR_CANCEL_VIOLATION           173L
#define ERROR_ATOMIC_LOCKS_NOT_SUPPORTED 174L
#define ERROR_INVALID_SEGMENT_NUMBER     180L
#define ERROR_INVALID_ORDINAL            182L
#define ERROR_ALREADY_EXISTS             183L
#define ERROR_INVALID_FLAG_NUMBER        186L
#define ERROR_SEM_NOT_FOUND              187L
#define ERROR_INVALID_STARTING_CODESEG   188L
#define ERROR_INVALID_STACKSEG           189L
#define ERROR_INVALID_MODULETYPE         190L
#define ERROR_INVALID_EXE_SIGNATURE      191L
#define ERROR_EXE_MARKED_INVALID         192L
#define ERROR_BAD_EXE_FORMAT             193L
#define ERROR_ITERATED_DATA_EXCEEDS_64k  194L
#define ERROR_INVALID_MINALLOCSIZE       195L
#define ERROR_DYNLINK_FROM_INVALID_RING  196L
#define ERROR_IOPL_NOT_ENABLED           197L
#define ERROR_INVALID_SEGDPL             198L
#define ERROR_AUTODATASEG_EXCEEDS_64k    199L
#define ERROR_RING2SEG_MUST_BE_MOVABLE   200L
#define ERROR_RELOC_CHAIN_XEEDS_SEGLIM   201L
#define ERROR_INFLOOP_IN_RELOC_CHAIN     202L
#define ERROR_ENVVAR_NOT_FOUND           203L
#define ERROR_NO_SIGNAL_SENT             205L
#define ERROR_FILENAME_EXCED_RANGE       206L
#define ERROR_RING2_STACK_IN_USE         207L
#define ERROR_META_EXPANSION_TOO_LONG    208L
#define ERROR_INVALID_SIGNAL_NUMBER      209L
#define ERROR_THREAD_1_INACTIVE          210L
#define ERROR_LOCKED                     212L
#define ERROR_TOO_MANY_MODULES           214L
#define ERROR_NESTING_NOT_ALLOWED        215L
#define ERROR_EXE_MACHINE_TYPE_MISMATCH  216L
#define ERROR_EXE_CANNOT_MODIFY_SIGNED_BINARY 217L
#define ERROR_EXE_CANNOT_MODIFY_STRONG_SIGNED_BINARY 218L
#define ERROR_FILE_CHECKED_OUT           220L
#define ERROR_CHECKOUT_REQUIRED          221L
#define ERROR_BAD_FILE_TYPE              222L
#define ERROR_FILE_TOO_LARGE             223L
#define ERROR_FORMS_AUTH_REQUIRED        224L
#define ERROR_VIRUS_INFECTED             225L
#define ERROR_VIRUS_DELETED              226L
#define ERROR_PIPE_LOCAL                 229L
#define ERROR_BAD_PIPE                   230L
#define ERROR_PIPE_BUSY                  231L
#define ERROR_NO_DATA                    232L
#define ERROR_PIPE_NOT_CONNECTED         233L
#define ERROR_MORE_DATA                  234L
#define ERROR_NO_WORK_DONE               235L
#define ERROR_VC_DISCONNECTED            240L
#define ERROR_INVALID_EA_NAME            254L
#define ERROR_EA_LIST_INCONSISTENT       255L
#define WAIT_TIMEOUT                     258L
#define ERROR_NO_MORE_ITEMS              259L
#define ERROR_CANNOT_COPY                266L
#define ERROR_DIRECTORY                  267L
#define ERROR_EAS_DIDNT_FIT              275L
#define ERROR_EA_FILE_CORRUPT            276L
#define ERROR_EA_TABLE_FULL              277L
#define ERROR_INVALID_EA_HANDLE          278L
#define ERROR_EAS_NOT_SUPPORTED          282L
#define ERROR_NOT_OWNER                  288L
#define ERROR_TOO_MANY_POSTS             298L
#define ERROR_PARTIAL_COPY               299L
#define ERROR_OPLOCK_NOT_GRANTED         300L
#define ERROR_INVALID_OPLOCK_PROTOCOL    301L
#define ERROR_DISK_TOO_FRAGMENTED        302L
#define ERROR_DELETE_PENDING             303L
#define ERROR_INCOMPATIBLE_WITH_GLOBAL_SHORT_NAME_REGISTRY_SETTING 304L
#define ERROR_SHORT_NAMES_NOT_ENABLED_ON_VOLUME 305L
#define ERROR_SECURITY_STREAM_IS_INCONSISTENT 306L
#define ERROR_INVALID_LOCK_RANGE         307L
#define ERROR_IMAGE_SUBSYSTEM_NOT_PRESENT 308L
#define ERROR_NOTIFICATION_GUID_ALREADY_DEFINED 309L
#define ERROR_INVALID_EXCEPTION_HANDLER  310L
#define ERROR_DUPLICATE_PRIVILEGES       311L
#define ERROR_NO_RANGES_PROCESSED        312L
#define ERROR_NOT_ALLOWED_ON_SYSTEM_FILE 313L
#define ERROR_DISK_RESOURCES_EXHAUSTED   314L
#define ERROR_INVALID_TOKEN              315L
#define ERROR_DEVICE_FEATURE_NOT_SUPPORTED 316L
#define ERROR_MR_MID_NOT_FOUND           317L
#define ERROR_SCOPE_NOT_FOUND            318L
#define ERROR_UNDEFINED_SCOPE            319L
#define ERROR_INVALID_CAP                320L
#define ERROR_DEVICE_UNREACHABLE         321L
#define ERROR_DEVICE_NO_RESOURCES        322L
#define ERROR_DATA_CHECKSUM_ERROR        323L
#define ERROR_INTERMIXED_KERNEL_EA_OPERATION 324L
#define ERROR_FILE_LEVEL_TRIM_NOT_SUPPORTED 326L
#define ERROR_OFFSET_ALIGNMENT_VIOLATION 327L
#define ERROR_INVALID_FIELD_IN_PARAMETER_LIST 328L
#define ERROR_OPERATION_IN_PROGRESS      329L
#define ERROR_BAD_DEVICE_PATH            330L
#define ERROR_TOO_MANY_DESCRIPTORS       331L
#define ERROR_SCRUB_DATA_DISABLED        332L
#define ERROR_NOT_REDUNDANT_STORAGE      333L
#define ERROR_RESIDENT_FILE_NOT_SUPPORTED 334L
#define ERROR_COMPRESSED_FILE_NOT_SUPPORTED 335L
#define ERROR_DIRECTORY_NOT_SUPPORTED    336L
#define ERROR_NOT_READ_FROM_COPY         337L
#define ERROR_FT_WRITE_FAILURE           338L
#define ERROR_FT_DI_SCAN_REQUIRED        339L
#define ERROR_INVALID_KERNEL_INFO_VERSION 340L
#define ERROR_INVALID_PEP_INFO_VERSION   341L
#define ERROR_OBJECT_NOT_EXTERNALLY_BACKED 342L
#define ERROR_EXTERNAL_BACKING_PROVIDER_UNKNOWN 343L
#define ERROR_COMPRESSION_NOT_BENEFICIAL 344L
#define ERROR_STORAGE_TOPOLOGY_ID_MISMATCH 345L
#define ERROR_BLOCKED_BY_PARENTAL_CONTROLS 346L
#define ERROR_BLOCK_TOO_MANY_REFERENCES  347L
#define ERROR_MARKED_TO_DISALLOW_WRITES  348L
#define ERROR_ENCLAVE_FAILURE            349L
#define ERROR_FAIL_NOACTION_REBOOT       350L
#define ERROR_FAIL_SHUTDOWN              351L
#define ERROR_FAIL_RESTART               352L
#define ERROR_MAX_SESSIONS_REACHED       353L
#define ERROR_NETWORK_ACCESS_DENIED_EDP  354L
#define ERROR_DEVICE_HINT_NAME_BUFFER_TOO_SMALL 355L
#define ERROR_EDP_POLICY_DENIES_OPERATION 356L
#define ERROR_EDP_DPL_POLICY_CANT_BE_SATISFIED 357L
#define ERROR_CLOUD_FILE_SYNC_ROOT_METADATA_CORRUPT 358L
#define ERROR_DEVICE_IN_MAINTENANCE      359L
#define ERROR_NOT_SUPPORTED_ON_DAX       360L
#define ERROR_DAX_MAPPING_EXISTS         361L
#define ERROR_CLOUD_FILE_PROVIDER_NOT_RUNNING 362L
#define ERROR_CLOUD_FILE_METADATA_CORRUPT 363L
#define ERROR_CLOUD_FILE_METADATA_TOO_LARGE 364L
#define ERROR_CLOUD_FILE_PROPERTY_BLOB_TOO_LARGE 365L
#define ERROR_CLOUD_FILE_PROPERTY_BLOB_CHECKSUM_MISMATCH 366L
#define ERROR_CHILD_PROCESS_BLOCKED      367L
#define ERROR_STORAGE_LOST_DATA_PERSISTENCE 368L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_UNAVAILABLE 369L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_METADATA_CORRUPT 370L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_BUSY 371L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_PROVIDER_UNKNOWN 372L
#define ERROR_GDI_HANDLE_LEAK            373L
#define ERROR_CLOUD_FILE_TOO_MANY_PROPERTY_BLOBS 374L
#define ERROR_CLOUD_FILE_PROPERTY_VERSION_NOT_SUPPORTED 375L
#define ERROR_NOT_A_CLOUD_FILE           376L
#define ERROR_CLOUD_FILE_NOT_IN_SYNC     377L
#define ERROR_CLOUD_FILE_ALREADY_CONNECTED 378L
#define ERROR_CLOUD_FILE_NOT_SUPPORTED   379L
#define ERROR_CLOUD_FILE_INVALID_REQUEST 380L
#define ERROR_CLOUD_FILE_READ_ONLY_VOLUME 381L
#define ERROR_CLOUD_FILE_CONNECTED_PROVIDER_ONLY 382L
#define ERROR_CLOUD_FILE_VALIDATION_FAILED 383L
#define ERROR_SMB1_NOT_AVAILABLE         384L
#define ERROR_FILE_SYSTEM_VIRTUALIZATION_INVALID_OPERATION 385L
#define ERROR_CLOUD_FILE_AUTHENTICATION_FAILED 386L
#define ERROR_CLOUD_FILE_INSUFFICIENT_RESOURCES 387L
#define ERROR_CLOUD_FILE_NETWORK_UNAVAILABLE 388L
#define ERROR_CLOUD_FILE_UNSUCCESSFUL    389L
#define ERROR_CLOUD_FILE_NOT_UNDER_SYNC_ROOT 390L
#define ERROR_CLOUD_FILE_IN_USE          391L
#define ERROR_CLOUD_FILE_PINNED          392L
#define ERROR_CLOUD_FILE_REQUEST_ABORTED 393L
#define ERROR_CLOUD_FILE_PROPERTY_CORRUPT 394L
#define ERROR_CLOUD_FILE_ACCESS_DENIED   395L
#define ERROR_CLOUD_FILE_INCOMPATIBLE_HARDLINKS 396L
#define ERROR_CLOUD_FILE_PROPERTY_LOCK_CONFLICT 397L
#define ERROR_CLOUD_FILE_REQUEST_CANCELED 398L
#define ERROR_EXTERNAL_SYSKEY_NOT_SUPPORTED 399L
#define ERROR_THREAD_MODE_ALREADY_BACKGROUND 400L
#define ERROR_THREAD_MODE_NOT_BACKGROUND 401L
#define ERROR_PROCESS_MODE_ALREADY_BACKGROUND 402L
#define ERROR_PROCESS_MODE_NOT_BACKGROUND 403L
#define ERROR_CLOUD_FILE_PROVIDER_TERMINATED 404L
#define ERROR_NOT_A_CLOUD_SYNC_ROOT      405L
#define ERROR_FILE_PROTECTED_UNDER_DPL   406L
#define ERROR_VOLUME_NOT_CLUSTER_ALIGNED 407L
#define ERROR_NO_PHYSICALLY_ALIGNED_FREE_SPACE_FOUND 408L
#define ERROR_APPX_FILE_NOT_ENCRYPTED    409L
#define ERROR_RWRAW_ENCRYPTED_FILE_NOT_ENCRYPTED 410L
#define ERROR_RWRAW_ENCRYPTED_INVALID_EDATAINFO_FILEOFFSET 411L
#define ERROR_RWRAW_ENCRYPTED_INVALID_EDATAINFO_FILERANGE 412L
#define ERROR_RWRAW_ENCRYPTED_INVALID_EDATAINFO_PARAMETER 413L
#define ERROR_LINUX_SUBSYSTEM_NOT_PRESENT 414L
#define ERROR_FT_READ_FAILURE            415L
#define ERROR_STORAGE_RESERVE_ID_INVALID 416L
#define ERROR_STORAGE_RESERVE_DOES_NOT_EXIST 417L
#define ERROR_STORAGE_RESERVE_ALREADY_EXISTS 418L
#define ERROR_STORAGE_RESERVE_NOT_EMPTY  419L
#define ERROR_NOT_A_DAX_VOLUME           420L
#define ERROR_NOT_DAX_MAPPABLE           421L
#define ERROR_TIME_SENSITIVE_THREAD      422L
#define ERROR_DPL_NOT_SUPPORTED_FOR_USER 423L
#define ERROR_CASE_DIFFERING_NAMES_IN_DIR 424L
#define ERROR_FILE_NOT_SUPPORTED         425L
#define ERROR_CLOUD_FILE_REQUEST_TIMEOUT 426L
#define ERROR_NO_TASK_QUEUE              427L
#define ERROR_SRC_SRV_DLL_LOAD_FAILED    428L
#define ERROR_NOT_SUPPORTED_WITH_BTT     429L
#define ERROR_ENCRYPTION_DISABLED        430L
#define ERROR_ENCRYPTING_METADATA_DISALLOWED 431L
#define ERROR_CANT_CLEAR_ENCRYPTION_FLAG 432L
#define ERROR_NO_SUCH_DEVICE             433L
#define ERROR_CLOUD_FILE_DEHYDRATION_DISALLOWED 434L
#define ERROR_FILE_SNAP_IN_PROGRESS      435L
#define ERROR_FILE_SNAP_USER_SECTION_NOT_SUPPORTED 436L
#define ERROR_FILE_SNAP_MODIFY_NOT_SUPPORTED 437L
#define ERROR_FILE_SNAP_IO_NOT_COORDINATED 438L
#define ERROR_FILE_SNAP_UNEXPECTED_ERROR 439L
#define ERROR_FILE_SNAP_INVALID_PARAMETER 440L
#define ERROR_UNSATISFIED_DEPENDENCIES   441L
#define ERROR_CASE_SENSITIVE_PATH        442L
#define ERROR_UNEXPECTED_NTCACHEMANAGER_ERROR 443L
#define ERROR_LINUX_SUBSYSTEM_UPDATE_REQUIRED 444L
#define ERROR_DLP_POLICY_WARNS_AGAINST_OPERATION 445L
#define ERROR_DLP_POLICY_DENIES_OPERATION 446L
#define ERROR_SECURITY_DENIES_OPERATION  447L
#define ERROR_UNTRUSTED_MOUNT_POINT      448L
#define ERROR_DLP_POLICY_SILENTLY_FAIL   449L
#define ERROR_CAPAUTHZ_NOT_DEVUNLOCKED   450L
#define ERROR_CAPAUTHZ_CHANGE_TYPE       451L
#define ERROR_CAPAUTHZ_NOT_PROVISIONED   452L
#define ERROR_CAPAUTHZ_NOT_AUTHORIZED    453L
#define ERROR_CAPAUTHZ_NO_POLICY         454L
#define ERROR_CAPAUTHZ_DB_CORRUPTED      455L
#define ERROR_CAPAUTHZ_SCCD_INVALID_CATALOG 456L
#define ERROR_CAPAUTHZ_SCCD_NO_AUTH_ENTITY 457L
#define ERROR_CAPAUTHZ_SCCD_PARSE_ERROR  458L
#define ERROR_CAPAUTHZ_SCCD_DEV_MODE_REQUIRED 459L
#define ERROR_CAPAUTHZ_SCCD_NO_CAPABILITY_MATCH 460L
#define ERROR_CIMFS_IMAGE_CORRUPT        470L
#define ERROR_CIMFS_IMAGE_VERSION_NOT_SUPPORTED 471L
#define ERROR_STORAGE_STACK_ACCESS_DENIED 472L
#define ERROR_INSUFFICIENT_VIRTUAL_ADDR_RESOURCES 473L
#define ERROR_INDEX_OUT_OF_BOUNDS        474L
#define ERROR_CLOUD_FILE_US_MESSAGE_TIMEOUT 475L
#define ERROR_NOT_A_DEV_VOLUME           476L
#define ERROR_FS_GUID_MISMATCH           477L
#define ERROR_CANT_ATTACH_TO_DEV_VOLUME  478L
#define ERROR_MEMORY_DECOMPRESSION_FAILURE 479L
#define ERROR_PNP_QUERY_REMOVE_DEVICE_TIMEOUT 480L
#define ERROR_PNP_QUERY_REMOVE_RELATED_DEVICE_TIMEOUT 481L
#define ERROR_PNP_QUERY_REMOVE_UNRELATED_DEVICE_TIMEOUT 482L
#define ERROR_DEVICE_HARDWARE_ERROR      483L
#define ERROR_INVALID_ADDRESS            487L
#define ERROR_OPERATION_ABORTED          995L
#define ERROR_IO_INCOMPLETE              996L
#define ERROR_IO_PENDING                 997L
#define ERROR_INVALID_FLAGS              1004L
#define ERROR_NO_TOKEN                   1008L
#define ERROR_CANTOPEN                   1011L
#define ERROR_NO_UNICODE_TRANSLATION     1113L
#define ERROR_IO_DEVICE                  1117L
#define ERROR_CONNECTION_UNAVAIL         1201L
#define ERROR_CANCELLED                  1223L
#define ERROR_USER_MAPPED_FILE           1224L
#define ERROR_CONNECTION_REFUSED         1225L
#define ERROR_ADDRESS_ALREADY_ASSOCIATED 1227L
#define ERROR_ADDRESS_NOT_ASSOCIATED     1228L
#define ERROR_CONNECTION_ABORTED         1236L
#define ERROR_NETWORK_UNREACHABLE        1231L
#define ERROR_HOST_UNREACHABLE           1232L
#define ERROR_PROTOCOL_UNREACHABLE       1233L
#define ERROR_INVALID_DOMAIN_STATE       1353L
#define ERROR_INVALID_DOMAIN_ROLE        1354L
#define ERROR_FILE_CORRUPT               1392L
#define ERROR_DISK_CORRUPT               1393L
#define ERROR_WORKING_SET_QUOTA          1453L
#define ERROR_TIMEOUT                    1460L
#define ERROR_INVALID_HANDLE_STATE       1609L
#define ERROR_NOT_CONNECTED              2250L
#define ERROR_DEVICE_IN_USE              2404L

#define NT_SUCCESS(Status) (((NTSTATUS)(Status)) >= 0)
#define NT_INFORMATION(Status) ((((ULONG)(Status)) >> 30) == 1)
#define NT_WARNING(Status) ((((ULONG)(Status)) >> 30) == 2)
#define NT_ERROR(Status) ((((ULONG)(Status)) >> 30) == 3)

#define STATUS_WAIT_0                    ((DWORD   )0x00000000L) 
#define STATUS_ABANDONED_WAIT_0          ((DWORD   )0x00000080L)
#define STATUS_USER_APC                  ((DWORD   )0x000000C0L)
#define STATUS_TIMEOUT                   ((DWORD   )0x00000102L)
#define STATUS_PENDING                   ((DWORD   )0x00000103L)
#define DBG_EXCEPTION_HANDLED            ((DWORD   )0x00010001L)
#define DBG_CONTINUE                     ((DWORD   )0x00010002L)
#define STATUS_SEGMENT_NOTIFICATION      ((DWORD   )0x40000005L)
#define STATUS_FATAL_APP_EXIT            ((DWORD   )0x40000015L)
#define DBG_REPLY_LATER                  ((DWORD   )0x40010001L)
#define DBG_TERMINATE_THREAD             ((DWORD   )0x40010003L)
#define DBG_TERMINATE_PROCESS            ((DWORD   )0x40010004L)
#define DBG_CONTROL_C                    ((DWORD   )0x40010005L)
#define DBG_PRINTEXCEPTION_C             ((DWORD   )0x40010006L)
#define DBG_RIPEXCEPTION                 ((DWORD   )0x40010007L)
#define DBG_CONTROL_BREAK                ((DWORD   )0x40010008L)
#define DBG_COMMAND_EXCEPTION            ((DWORD   )0x40010009L)
#define DBG_PRINTEXCEPTION_WIDE_C        ((DWORD   )0x4001000AL)
#define STATUS_GUARD_PAGE_VIOLATION      ((DWORD   )0x80000001L)
#define STATUS_DATATYPE_MISALIGNMENT     ((DWORD   )0x80000002L)
#define STATUS_BREAKPOINT                ((DWORD   )0x80000003L)
#define STATUS_SINGLE_STEP               ((DWORD   )0x80000004L)
#define STATUS_LONGJUMP                  ((DWORD   )0x80000026L)
#define STATUS_UNWIND                    ((NTSTATUS)0xC0000027L)
#define STATUS_UNWIND_CONSOLIDATE        ((DWORD   )0x80000029L)
#define DBG_EXCEPTION_NOT_HANDLED        ((DWORD   )0x80010001L)
#define STATUS_ACCESS_VIOLATION          ((DWORD   )0xC0000005L)
#define STATUS_IN_PAGE_ERROR             ((DWORD   )0xC0000006L)
#define STATUS_INVALID_HANDLE            ((DWORD   )0xC0000008L)
#define STATUS_INVALID_PARAMETER         ((DWORD   )0xC000000DL)
#define STATUS_NO_MEMORY                 ((DWORD   )0xC0000017L)
#define STATUS_ILLEGAL_INSTRUCTION       ((DWORD   )0xC000001DL)
#define STATUS_NONCONTINUABLE_EXCEPTION  ((DWORD   )0xC0000025L)
#define STATUS_INVALID_DISPOSITION       ((DWORD   )0xC0000026L)
#define STATUS_ARRAY_BOUNDS_EXCEEDED     ((DWORD   )0xC000008CL)
#define STATUS_FLOAT_DENORMAL_OPERAND    ((DWORD   )0xC000008DL)
#define STATUS_FLOAT_DIVIDE_BY_ZERO      ((DWORD   )0xC000008EL)
#define STATUS_FLOAT_INEXACT_RESULT      ((DWORD   )0xC000008FL)
#define STATUS_FLOAT_INVALID_OPERATION   ((DWORD   )0xC0000090L)
#define STATUS_FLOAT_OVERFLOW            ((DWORD   )0xC0000091L)
#define STATUS_FLOAT_STACK_CHECK         ((DWORD   )0xC0000092L)
#define STATUS_FLOAT_UNDERFLOW           ((DWORD   )0xC0000093L)
#define STATUS_INTEGER_DIVIDE_BY_ZERO    ((DWORD   )0xC0000094L)
#define STATUS_INTEGER_OVERFLOW          ((DWORD   )0xC0000095L)
#define STATUS_PRIVILEGED_INSTRUCTION    ((DWORD   )0xC0000096L)
#define STATUS_STACK_OVERFLOW            ((DWORD   )0xC00000FDL)
#define STATUS_DLL_NOT_FOUND             ((DWORD   )0xC0000135L)
#define STATUS_ORDINAL_NOT_FOUND         ((DWORD   )0xC0000138L)
#define STATUS_ENTRYPOINT_NOT_FOUND      ((DWORD   )0xC0000139L)
#define STATUS_CONTROL_C_EXIT            ((DWORD   )0xC000013AL)
#define STATUS_DLL_INIT_FAILED           ((DWORD   )0xC0000142L)
#define STATUS_CONTROL_STACK_VIOLATION   ((DWORD   )0xC00001B2L)
#define STATUS_FLOAT_MULTIPLE_FAULTS     ((DWORD   )0xC00002B4L)
#define STATUS_FLOAT_MULTIPLE_TRAPS      ((DWORD   )0xC00002B5L)
#define STATUS_REG_NAT_CONSUMPTION       ((DWORD   )0xC00002C9L)
#define STATUS_HEAP_CORRUPTION           ((DWORD   )0xC0000374L)
#define STATUS_STACK_BUFFER_OVERRUN      ((DWORD   )0xC0000409L)
#define STATUS_INVALID_CRUNTIME_PARAMETER ((DWORD   )0xC0000417L)
#define STATUS_ASSERTION_FAILURE         ((DWORD   )0xC0000420L)
#define STATUS_ENCLAVE_VIOLATION         ((DWORD   )0xC00004A2L)
#define STATUS_INTERRUPTED               ((DWORD   )0xC0000515L)
#define STATUS_THREAD_NOT_RUNNING        ((DWORD   )0xC0000516L)
#define STATUS_ALREADY_REGISTERED        ((DWORD   )0xC0000718L)
#define STATUS_SXS_EARLY_DEACTIVATION    ((DWORD   )0xC015000FL)
#define STATUS_SXS_INVALID_DEACTIVATION  ((DWORD   )0xC0150010L)

#define STATUS_POSSIBLE_DEADLOCK         ((NTSTATUS)0xC0000194L)
#define STATUS_OBJECT_TYPE_MISMATCH      ((NTSTATUS)0xC0000024L)

#define STATUS_INVALID_PARAMETER_1       ((NTSTATUS)0xC00000EFL)
#define STATUS_INVALID_PARAMETER_2       ((NTSTATUS)0xC00000F0L)
#define STATUS_INVALID_PARAMETER_3       ((NTSTATUS)0xC00000F1L)
#define STATUS_INVALID_PARAMETER_4       ((NTSTATUS)0xC00000F2L)
#define STATUS_INVALID_PARAMETER_5       ((NTSTATUS)0xC00000F3L)
#define STATUS_INVALID_PARAMETER_6       ((NTSTATUS)0xC00000F4L)
#define STATUS_INVALID_PARAMETER_7       ((NTSTATUS)0xC00000F5L)
#define STATUS_INVALID_PARAMETER_8       ((NTSTATUS)0xC00000F6L)
#define STATUS_INVALID_PARAMETER_9       ((NTSTATUS)0xC00000F7L)
#define STATUS_INVALID_PARAMETER_10      ((NTSTATUS)0xC00000F8L)
#define STATUS_INVALID_PARAMETER_11      ((NTSTATUS)0xC00000F9L)
#define STATUS_INVALID_PARAMETER_12      ((NTSTATUS)0xC00000FAL)

#define FACILITY_WIN32                   7

#define S_OK                            ((HRESULT)0L)

#define __HRESULT_FROM_WIN32(x) ((HRESULT)(x) <= 0 ? ((HRESULT)(x)) : ((HRESULT) (((x) & 0x0000FFFF) | (FACILITY_WIN32 << 16) | 0x80000000)))

#define CRYPT_E_MSG_ERROR                _HRESULT_TYPEDEF_(0x80091001L)
#define CRYPT_E_UNKNOWN_ALGO             _HRESULT_TYPEDEF_(0x80091002L)
#define CRYPT_E_OID_FORMAT               _HRESULT_TYPEDEF_(0x80091003L)
#define CRYPT_E_INVALID_MSG_TYPE         _HRESULT_TYPEDEF_(0x80091004L)
#define CRYPT_E_UNEXPECTED_ENCODING      _HRESULT_TYPEDEF_(0x80091005L)
#define CRYPT_E_AUTH_ATTR_MISSING        _HRESULT_TYPEDEF_(0x80091006L)
#define CRYPT_E_HASH_VALUE               _HRESULT_TYPEDEF_(0x80091007L)
#define CRYPT_E_INVALID_INDEX            _HRESULT_TYPEDEF_(0x80091008L)
#define CRYPT_E_ALREADY_DECRYPTED        _HRESULT_TYPEDEF_(0x80091009L)
#define CRYPT_E_NOT_DECRYPTED            _HRESULT_TYPEDEF_(0x8009100AL)
#define CRYPT_E_RECIPIENT_NOT_FOUND      _HRESULT_TYPEDEF_(0x8009100BL)
#define CRYPT_E_CONTROL_TYPE             _HRESULT_TYPEDEF_(0x8009100CL)
#define CRYPT_E_ISSUER_SERIALNUMBER      _HRESULT_TYPEDEF_(0x8009100DL)
#define CRYPT_E_SIGNER_NOT_FOUND         _HRESULT_TYPEDEF_(0x8009100EL)
#define CRYPT_E_ATTRIBUTES_MISSING       _HRESULT_TYPEDEF_(0x8009100FL)
#define CRYPT_E_STREAM_MSG_NOT_READY     _HRESULT_TYPEDEF_(0x80091010L)
#define CRYPT_E_STREAM_INSUFFICIENT_DATA _HRESULT_TYPEDEF_(0x80091011L)
#define CRYPT_I_NEW_PROTECTION_REQUIRED  _HRESULT_TYPEDEF_(0x00091012L)
#define CRYPT_E_BAD_LEN                  _HRESULT_TYPEDEF_(0x80092001L)
#define CRYPT_E_BAD_ENCODE               _HRESULT_TYPEDEF_(0x80092002L)
#define CRYPT_E_FILE_ERROR               _HRESULT_TYPEDEF_(0x80092003L)
#define CRYPT_E_NOT_FOUND                _HRESULT_TYPEDEF_(0x80092004L)
#define CRYPT_E_EXISTS                   _HRESULT_TYPEDEF_(0x80092005L)
#define CRYPT_E_NO_PROVIDER              _HRESULT_TYPEDEF_(0x80092006L)
#define CRYPT_E_SELF_SIGNED              _HRESULT_TYPEDEF_(0x80092007L)
#define CRYPT_E_DELETED_PREV             _HRESULT_TYPEDEF_(0x80092008L)
#define CRYPT_E_NO_MATCH                 _HRESULT_TYPEDEF_(0x80092009L)
#define CRYPT_E_UNEXPECTED_MSG_TYPE      _HRESULT_TYPEDEF_(0x8009200AL)
#define CRYPT_E_NO_KEY_PROPERTY          _HRESULT_TYPEDEF_(0x8009200BL)
#define CRYPT_E_NO_DECRYPT_CERT          _HRESULT_TYPEDEF_(0x8009200CL)
#define CRYPT_E_BAD_MSG                  _HRESULT_TYPEDEF_(0x8009200DL)
#define CRYPT_E_NO_SIGNER                _HRESULT_TYPEDEF_(0x8009200EL)
#define CRYPT_E_PENDING_CLOSE            _HRESULT_TYPEDEF_(0x8009200FL)
#define CRYPT_E_REVOKED                  _HRESULT_TYPEDEF_(0x80092010L)
#define CRYPT_E_NO_REVOCATION_DLL        _HRESULT_TYPEDEF_(0x80092011L)
#define CRYPT_E_NO_REVOCATION_CHECK      _HRESULT_TYPEDEF_(0x80092012L)
#define CRYPT_E_REVOCATION_OFFLINE       _HRESULT_TYPEDEF_(0x80092013L)
#define CRYPT_E_NOT_IN_REVOCATION_DATABASE _HRESULT_TYPEDEF_(0x80092014L)
#define CRYPT_E_INVALID_NUMERIC_STRING   _HRESULT_TYPEDEF_(0x80092020L)
#define CRYPT_E_INVALID_PRINTABLE_STRING _HRESULT_TYPEDEF_(0x80092021L)
#define CRYPT_E_INVALID_IA5_STRING       _HRESULT_TYPEDEF_(0x80092022L)
#define CRYPT_E_INVALID_X500_STRING      _HRESULT_TYPEDEF_(0x80092023L)
#define CRYPT_E_NOT_CHAR_STRING          _HRESULT_TYPEDEF_(0x80092024L)
#define CRYPT_E_FILERESIZED              _HRESULT_TYPEDEF_(0x80092025L)
#define CRYPT_E_SECURITY_SETTINGS        _HRESULT_TYPEDEF_(0x80092026L)
#define CRYPT_E_NO_VERIFY_USAGE_DLL      _HRESULT_TYPEDEF_(0x80092027L)
#define CRYPT_E_NO_VERIFY_USAGE_CHECK    _HRESULT_TYPEDEF_(0x80092028L)
#define CRYPT_E_VERIFY_USAGE_OFFLINE     _HRESULT_TYPEDEF_(0x80092029L)
#define CRYPT_E_NOT_IN_CTL               _HRESULT_TYPEDEF_(0x8009202AL)
#define CRYPT_E_NO_TRUSTED_SIGNER        _HRESULT_TYPEDEF_(0x8009202BL)
#define CRYPT_E_MISSING_PUBKEY_PARA      _HRESULT_TYPEDEF_(0x8009202CL)
#define CRYPT_E_OBJECT_LOCATOR_OBJECT_NOT_FOUND _HRESULT_TYPEDEF_(0x8009202DL)
#define CRYPT_E_OSS_ERROR                _HRESULT_TYPEDEF_(0x80093000L)

// clang-format on

#define HRESULT_FROM_WIN32(x) __HRESULT_FROM_WIN32(x)

#endif // SPRT_WRAPPERS_WINDOWS_ERRORS_H_
