#define __SPRT_SYSCALL_read 0
#define __SPRT_SYSCALL_write 1
#define __SPRT_SYSCALL_open 2
#define __SPRT_SYSCALL_close 3
#define __SPRT_SYSCALL_stat 4
#define __SPRT_SYSCALL_fstat 5
#define __SPRT_SYSCALL_lstat 6
#define __SPRT_SYSCALL_poll 7
#define __SPRT_SYSCALL_lseek 8
#define __SPRT_SYSCALL_mmap 9
#define __SPRT_SYSCALL_mprotect 10
#define __SPRT_SYSCALL_munmap 11
#define __SPRT_SYSCALL_brk 12
#define __SPRT_SYSCALL_rt_sigaction 13
#define __SPRT_SYSCALL_rt_sigprocmask 14
#define __SPRT_SYSCALL_rt_sigreturn 15
#define __SPRT_SYSCALL_ioctl 16
#define __SPRT_SYSCALL_pread64 17
#define __SPRT_SYSCALL_pwrite64 18
#define __SPRT_SYSCALL_readv 19
#define __SPRT_SYSCALL_writev 20
#define __SPRT_SYSCALL_access 21
#define __SPRT_SYSCALL_pipe 22
#define __SPRT_SYSCALL_select 23
#define __SPRT_SYSCALL_sched_yield 24
#define __SPRT_SYSCALL_mremap 25
#define __SPRT_SYSCALL_msync 26
#define __SPRT_SYSCALL_mincore 27
#define __SPRT_SYSCALL_madvise 28
#define __SPRT_SYSCALL_shmget 29
#define __SPRT_SYSCALL_shmat 30
#define __SPRT_SYSCALL_shmctl 31
#define __SPRT_SYSCALL_dup 32
#define __SPRT_SYSCALL_dup2 33
#define __SPRT_SYSCALL_pause 34
#define __SPRT_SYSCALL_nanosleep 35
#define __SPRT_SYSCALL_getitimer 36
#define __SPRT_SYSCALL_alarm 37
#define __SPRT_SYSCALL_setitimer 38
#define __SPRT_SYSCALL_getpid 39
#define __SPRT_SYSCALL_sendfile 40
#define __SPRT_SYSCALL_socket 41
#define __SPRT_SYSCALL_connect 42
#define __SPRT_SYSCALL_accept 43
#define __SPRT_SYSCALL_sendto 44
#define __SPRT_SYSCALL_recvfrom 45
#define __SPRT_SYSCALL_sendmsg 46
#define __SPRT_SYSCALL_recvmsg 47
#define __SPRT_SYSCALL_shutdown 48
#define __SPRT_SYSCALL_bind 49
#define __SPRT_SYSCALL_listen 50
#define __SPRT_SYSCALL_getsockname 51
#define __SPRT_SYSCALL_getpeername 52
#define __SPRT_SYSCALL_socketpair 53
#define __SPRT_SYSCALL_setsockopt 54
#define __SPRT_SYSCALL_getsockopt 55
#define __SPRT_SYSCALL_clone 56
#define __SPRT_SYSCALL_fork 57
#define __SPRT_SYSCALL_vfork 58
#define __SPRT_SYSCALL_execve 59
#define __SPRT_SYSCALL_exit 60
#define __SPRT_SYSCALL_wait4 61
#define __SPRT_SYSCALL_kill 62
#define __SPRT_SYSCALL_uname 63
#define __SPRT_SYSCALL_semget 64
#define __SPRT_SYSCALL_semop 65
#define __SPRT_SYSCALL_semctl 66
#define __SPRT_SYSCALL_shmdt 67
#define __SPRT_SYSCALL_msgget 68
#define __SPRT_SYSCALL_msgsnd 69
#define __SPRT_SYSCALL_msgrcv 70
#define __SPRT_SYSCALL_msgctl 71
#define __SPRT_SYSCALL_fcntl 72
#define __SPRT_SYSCALL_flock 73
#define __SPRT_SYSCALL_fsync 74
#define __SPRT_SYSCALL_fdatasync 75
#define __SPRT_SYSCALL_truncate 76
#define __SPRT_SYSCALL_ftruncate 77
#define __SPRT_SYSCALL_getdents 78
#define __SPRT_SYSCALL_getcwd 79
#define __SPRT_SYSCALL_chdir 80
#define __SPRT_SYSCALL_fchdir 81
#define __SPRT_SYSCALL_rename 82
#define __SPRT_SYSCALL_mkdir 83
#define __SPRT_SYSCALL_rmdir 84
#define __SPRT_SYSCALL_creat 85
#define __SPRT_SYSCALL_link 86
#define __SPRT_SYSCALL_unlink 87
#define __SPRT_SYSCALL_symlink 88
#define __SPRT_SYSCALL_readlink 89
#define __SPRT_SYSCALL_chmod 90
#define __SPRT_SYSCALL_fchmod 91
#define __SPRT_SYSCALL_chown 92
#define __SPRT_SYSCALL_fchown 93
#define __SPRT_SYSCALL_lchown 94
#define __SPRT_SYSCALL_umask 95
#define __SPRT_SYSCALL_gettimeofday 96
#define __SPRT_SYSCALL_getrlimit 97
#define __SPRT_SYSCALL_getrusage 98
#define __SPRT_SYSCALL_sysinfo 99
#define __SPRT_SYSCALL_times 100
#define __SPRT_SYSCALL_ptrace 101
#define __SPRT_SYSCALL_getuid 102
#define __SPRT_SYSCALL_syslog 103
#define __SPRT_SYSCALL_getgid 104
#define __SPRT_SYSCALL_setuid 105
#define __SPRT_SYSCALL_setgid 106
#define __SPRT_SYSCALL_geteuid 107
#define __SPRT_SYSCALL_getegid 108
#define __SPRT_SYSCALL_setpgid 109
#define __SPRT_SYSCALL_getppid 110
#define __SPRT_SYSCALL_getpgrp 111
#define __SPRT_SYSCALL_setsid 112
#define __SPRT_SYSCALL_setreuid 113
#define __SPRT_SYSCALL_setregid 114
#define __SPRT_SYSCALL_getgroups 115
#define __SPRT_SYSCALL_setgroups 116
#define __SPRT_SYSCALL_setresuid 117
#define __SPRT_SYSCALL_getresuid 118
#define __SPRT_SYSCALL_setresgid 119
#define __SPRT_SYSCALL_getresgid 120
#define __SPRT_SYSCALL_getpgid 121
#define __SPRT_SYSCALL_setfsuid 122
#define __SPRT_SYSCALL_setfsgid 123
#define __SPRT_SYSCALL_getsid 124
#define __SPRT_SYSCALL_capget 125
#define __SPRT_SYSCALL_capset 126
#define __SPRT_SYSCALL_rt_sigpending 127
#define __SPRT_SYSCALL_rt_sigtimedwait 128
#define __SPRT_SYSCALL_rt_sigqueueinfo 129
#define __SPRT_SYSCALL_rt_sigsuspend 130
#define __SPRT_SYSCALL_sigaltstack 131
#define __SPRT_SYSCALL_utime 132
#define __SPRT_SYSCALL_mknod 133
#define __SPRT_SYSCALL_uselib 134
#define __SPRT_SYSCALL_personality 135
#define __SPRT_SYSCALL_ustat 136
#define __SPRT_SYSCALL_statfs 137
#define __SPRT_SYSCALL_fstatfs 138
#define __SPRT_SYSCALL_sysfs 139
#define __SPRT_SYSCALL_getpriority 140
#define __SPRT_SYSCALL_setpriority 141
#define __SPRT_SYSCALL_sched_setparam 142
#define __SPRT_SYSCALL_sched_getparam 143
#define __SPRT_SYSCALL_sched_setscheduler 144
#define __SPRT_SYSCALL_sched_getscheduler 145
#define __SPRT_SYSCALL_sched_get_priority_max 146
#define __SPRT_SYSCALL_sched_get_priority_min 147
#define __SPRT_SYSCALL_sched_rr_get_interval 148
#define __SPRT_SYSCALL_mlock 149
#define __SPRT_SYSCALL_munlock 150
#define __SPRT_SYSCALL_mlockall 151
#define __SPRT_SYSCALL_munlockall 152
#define __SPRT_SYSCALL_vhangup 153
#define __SPRT_SYSCALL_modify_ldt 154
#define __SPRT_SYSCALL_pivot_root 155
#define __SPRT_SYSCALL__sysctl 156
#define __SPRT_SYSCALL_prctl 157
#define __SPRT_SYSCALL_arch_prctl 158
#define __SPRT_SYSCALL_adjtimex 159
#define __SPRT_SYSCALL_setrlimit 160
#define __SPRT_SYSCALL_chroot 161
#define __SPRT_SYSCALL_sync 162
#define __SPRT_SYSCALL_acct 163
#define __SPRT_SYSCALL_settimeofday 164
#define __SPRT_SYSCALL_mount 165
#define __SPRT_SYSCALL_umount2 166
#define __SPRT_SYSCALL_swapon 167
#define __SPRT_SYSCALL_swapoff 168
#define __SPRT_SYSCALL_reboot 169
#define __SPRT_SYSCALL_sethostname 170
#define __SPRT_SYSCALL_setdomainname 171
#define __SPRT_SYSCALL_iopl 172
#define __SPRT_SYSCALL_ioperm 173
#define __SPRT_SYSCALL_create_module 174
#define __SPRT_SYSCALL_init_module 175
#define __SPRT_SYSCALL_delete_module 176
#define __SPRT_SYSCALL_get_kernel_syms 177
#define __SPRT_SYSCALL_query_module 178
#define __SPRT_SYSCALL_quotactl 179
#define __SPRT_SYSCALL_nfsservctl 180
#define __SPRT_SYSCALL_getpmsg 181
#define __SPRT_SYSCALL_putpmsg 182
#define __SPRT_SYSCALL_afs_syscall 183
#define __SPRT_SYSCALL_tuxcall 184
#define __SPRT_SYSCALL_security 185
#define __SPRT_SYSCALL_gettid 186
#define __SPRT_SYSCALL_readahead 187
#define __SPRT_SYSCALL_setxattr 188
#define __SPRT_SYSCALL_lsetxattr 189
#define __SPRT_SYSCALL_fsetxattr 190
#define __SPRT_SYSCALL_getxattr 191
#define __SPRT_SYSCALL_lgetxattr 192
#define __SPRT_SYSCALL_fgetxattr 193
#define __SPRT_SYSCALL_listxattr 194
#define __SPRT_SYSCALL_llistxattr 195
#define __SPRT_SYSCALL_flistxattr 196
#define __SPRT_SYSCALL_removexattr 197
#define __SPRT_SYSCALL_lremovexattr 198
#define __SPRT_SYSCALL_fremovexattr 199
#define __SPRT_SYSCALL_tkill 200
#define __SPRT_SYSCALL_time 201
#define __SPRT_SYSCALL_futex 202
#define __SPRT_SYSCALL_sched_setaffinity 203
#define __SPRT_SYSCALL_sched_getaffinity 204
#define __SPRT_SYSCALL_set_thread_area 205
#define __SPRT_SYSCALL_io_setup 206
#define __SPRT_SYSCALL_io_destroy 207
#define __SPRT_SYSCALL_io_getevents 208
#define __SPRT_SYSCALL_io_submit 209
#define __SPRT_SYSCALL_io_cancel 210
#define __SPRT_SYSCALL_get_thread_area 211
#define __SPRT_SYSCALL_lookup_dcookie 212
#define __SPRT_SYSCALL_epoll_create 213
#define __SPRT_SYSCALL_epoll_ctl_old 214
#define __SPRT_SYSCALL_epoll_wait_old 215
#define __SPRT_SYSCALL_remap_file_pages 216
#define __SPRT_SYSCALL_getdents64 217
#define __SPRT_SYSCALL_set_tid_address 218
#define __SPRT_SYSCALL_restart_syscall 219
#define __SPRT_SYSCALL_semtimedop 220
#define __SPRT_SYSCALL_fadvise64 221
#define __SPRT_SYSCALL_timer_create 222
#define __SPRT_SYSCALL_timer_settime 223
#define __SPRT_SYSCALL_timer_gettime 224
#define __SPRT_SYSCALL_timer_getoverrun 225
#define __SPRT_SYSCALL_timer_delete 226
#define __SPRT_SYSCALL_clock_settime 227
#define __SPRT_SYSCALL_clock_gettime 228
#define __SPRT_SYSCALL_clock_getres 229
#define __SPRT_SYSCALL_clock_nanosleep 230
#define __SPRT_SYSCALL_exit_group 231
#define __SPRT_SYSCALL_epoll_wait 232
#define __SPRT_SYSCALL_epoll_ctl 233
#define __SPRT_SYSCALL_tgkill 234
#define __SPRT_SYSCALL_utimes 235
#define __SPRT_SYSCALL_vserver 236
#define __SPRT_SYSCALL_mbind 237
#define __SPRT_SYSCALL_set_mempolicy 238
#define __SPRT_SYSCALL_get_mempolicy 239
#define __SPRT_SYSCALL_mq_open 240
#define __SPRT_SYSCALL_mq_unlink 241
#define __SPRT_SYSCALL_mq_timedsend 242
#define __SPRT_SYSCALL_mq_timedreceive 243
#define __SPRT_SYSCALL_mq_notify 244
#define __SPRT_SYSCALL_mq_getsetattr 245
#define __SPRT_SYSCALL_kexec_load 246
#define __SPRT_SYSCALL_waitid 247
#define __SPRT_SYSCALL_add_key 248
#define __SPRT_SYSCALL_request_key 249
#define __SPRT_SYSCALL_keyctl 250
#define __SPRT_SYSCALL_ioprio_set 251
#define __SPRT_SYSCALL_ioprio_get 252
#define __SPRT_SYSCALL_inotify_init 253
#define __SPRT_SYSCALL_inotify_add_watch 254
#define __SPRT_SYSCALL_inotify_rm_watch 255
#define __SPRT_SYSCALL_migrate_pages 256
#define __SPRT_SYSCALL_openat 257
#define __SPRT_SYSCALL_mkdirat 258
#define __SPRT_SYSCALL_mknodat 259
#define __SPRT_SYSCALL_fchownat 260
#define __SPRT_SYSCALL_futimesat 261
#define __SPRT_SYSCALL_newfstatat 262
#define __SPRT_SYSCALL_unlinkat 263
#define __SPRT_SYSCALL_renameat 264
#define __SPRT_SYSCALL_linkat 265
#define __SPRT_SYSCALL_symlinkat 266
#define __SPRT_SYSCALL_readlinkat 267
#define __SPRT_SYSCALL_fchmodat 268
#define __SPRT_SYSCALL_faccessat 269
#define __SPRT_SYSCALL_pselect6 270
#define __SPRT_SYSCALL_ppoll 271
#define __SPRT_SYSCALL_unshare 272
#define __SPRT_SYSCALL_set_robust_list 273
#define __SPRT_SYSCALL_get_robust_list 274
#define __SPRT_SYSCALL_splice 275
#define __SPRT_SYSCALL_tee 276
#define __SPRT_SYSCALL_sync_file_range 277
#define __SPRT_SYSCALL_vmsplice 278
#define __SPRT_SYSCALL_move_pages 279
#define __SPRT_SYSCALL_utimensat 280
#define __SPRT_SYSCALL_epoll_pwait 281
#define __SPRT_SYSCALL_signalfd 282
#define __SPRT_SYSCALL_timerfd_create 283
#define __SPRT_SYSCALL_eventfd 284
#define __SPRT_SYSCALL_fallocate 285
#define __SPRT_SYSCALL_timerfd_settime 286
#define __SPRT_SYSCALL_timerfd_gettime 287
#define __SPRT_SYSCALL_accept4 288
#define __SPRT_SYSCALL_signalfd4 289
#define __SPRT_SYSCALL_eventfd2 290
#define __SPRT_SYSCALL_epoll_create1 291
#define __SPRT_SYSCALL_dup3 292
#define __SPRT_SYSCALL_pipe2 293
#define __SPRT_SYSCALL_inotify_init1 294
#define __SPRT_SYSCALL_preadv 295
#define __SPRT_SYSCALL_pwritev 296
#define __SPRT_SYSCALL_rt_tgsigqueueinfo 297
#define __SPRT_SYSCALL_perf_event_open 298
#define __SPRT_SYSCALL_recvmmsg 299
#define __SPRT_SYSCALL_fanotify_init 300
#define __SPRT_SYSCALL_fanotify_mark 301
#define __SPRT_SYSCALL_prlimit64 302
#define __SPRT_SYSCALL_name_to_handle_at 303
#define __SPRT_SYSCALL_open_by_handle_at 304
#define __SPRT_SYSCALL_clock_adjtime 305
#define __SPRT_SYSCALL_syncfs 306
#define __SPRT_SYSCALL_sendmmsg 307
#define __SPRT_SYSCALL_setns 308
#define __SPRT_SYSCALL_getcpu 309
#define __SPRT_SYSCALL_process_vm_readv 310
#define __SPRT_SYSCALL_process_vm_writev 311
#define __SPRT_SYSCALL_kcmp 312
#define __SPRT_SYSCALL_finit_module 313
#define __SPRT_SYSCALL_sched_setattr 314
#define __SPRT_SYSCALL_sched_getattr 315
#define __SPRT_SYSCALL_renameat2 316
#define __SPRT_SYSCALL_seccomp 317
#define __SPRT_SYSCALL_getrandom 318
#define __SPRT_SYSCALL_memfd_create 319
#define __SPRT_SYSCALL_kexec_file_load 320
#define __SPRT_SYSCALL_bpf 321
#define __SPRT_SYSCALL_execveat 322
#define __SPRT_SYSCALL_userfaultfd 323
#define __SPRT_SYSCALL_membarrier 324
#define __SPRT_SYSCALL_mlock2 325
#define __SPRT_SYSCALL_copy_file_range 326
#define __SPRT_SYSCALL_preadv2 327
#define __SPRT_SYSCALL_pwritev2 328
#define __SPRT_SYSCALL_pkey_mprotect 329
#define __SPRT_SYSCALL_pkey_alloc 330
#define __SPRT_SYSCALL_pkey_free 331
#define __SPRT_SYSCALL_statx 332
#define __SPRT_SYSCALL_io_pgetevents 333
#define __SPRT_SYSCALL_rseq 334
#define __SPRT_SYSCALL_uretprobe 335
#define __SPRT_SYSCALL_uprobe 336
#define __SPRT_SYSCALL_pidfd_send_signal 424
#define __SPRT_SYSCALL_io_uring_setup 425
#define __SPRT_SYSCALL_io_uring_enter 426
#define __SPRT_SYSCALL_io_uring_register 427
#define __SPRT_SYSCALL_open_tree 428
#define __SPRT_SYSCALL_move_mount 429
#define __SPRT_SYSCALL_fsopen 430
#define __SPRT_SYSCALL_fsconfig 431
#define __SPRT_SYSCALL_fsmount 432
#define __SPRT_SYSCALL_fspick 433
#define __SPRT_SYSCALL_pidfd_open 434
#define __SPRT_SYSCALL_clone3 435
#define __SPRT_SYSCALL_close_range 436
#define __SPRT_SYSCALL_openat2 437
#define __SPRT_SYSCALL_pidfd_getfd 438
#define __SPRT_SYSCALL_faccessat2 439
#define __SPRT_SYSCALL_process_madvise 440
#define __SPRT_SYSCALL_epoll_pwait2 441
#define __SPRT_SYSCALL_mount_setattr 442
#define __SPRT_SYSCALL_quotactl_fd 443
#define __SPRT_SYSCALL_landlock_create_ruleset 444
#define __SPRT_SYSCALL_landlock_add_rule 445
#define __SPRT_SYSCALL_landlock_restrict_self 446
#define __SPRT_SYSCALL_memfd_secret 447
#define __SPRT_SYSCALL_process_mrelease 448
#define __SPRT_SYSCALL_futex_waitv 449
#define __SPRT_SYSCALL_set_mempolicy_home_node 450
#define __SPRT_SYSCALL_cachestat 451
#define __SPRT_SYSCALL_fchmodat2 452
#define __SPRT_SYSCALL_map_shadow_stack 453
#define __SPRT_SYSCALL_futex_wake 454
#define __SPRT_SYSCALL_futex_wait 455
#define __SPRT_SYSCALL_futex_requeue 456
#define __SPRT_SYSCALL_statmount 457
#define __SPRT_SYSCALL_listmount 458
#define __SPRT_SYSCALL_lsm_get_self_attr 459
#define __SPRT_SYSCALL_lsm_set_self_attr 460
#define __SPRT_SYSCALL_lsm_list_modules 461
#define __SPRT_SYSCALL_mseal 462
#define __SPRT_SYSCALL_setxattrat 463
#define __SPRT_SYSCALL_getxattrat 464
#define __SPRT_SYSCALL_listxattrat 465
#define __SPRT_SYSCALL_removexattrat 466
#define __SPRT_SYSCALL_open_tree_attr 467
#define __SPRT_SYSCALL_file_getattr 468
#define __SPRT_SYSCALL_file_setattr 469
