#ifndef CORE_RUNTIME_INCLUDE_SPRT_WRAPPERS_LIBC_INTTYPES_H_
#define CORE_RUNTIME_INCLUDE_SPRT_WRAPPERS_LIBC_INTTYPES_H_

#include <sprt/wrappers/libc/stdint.h>

#if __STDC_HOSTED__ == 0 || !defined(__SPRT_BUILD)

#define PRId8		__SPRT_INT8_FMTd
#define PRId16		__SPRT_INT16_FMTd
#define PRId32		__SPRT_INT32_FMTd
#define PRId64		__SPRT_INT64_FMTd
#define PRIdLEAST8  __SPRT_INT_LEAST8_FMTd
#define PRIdLEAST16 __SPRT_INT_LEAST16_FMTd
#define PRIdLEAST32 __SPRT_INT_LEAST32_FMTd
#define PRIdLEAST64 __SPRT_INT_LEAST64_FMTd
#define PRIdFAST8   __SPRT_INT_FAST8_FMTd
#define PRIdFAST16  __SPRT_INT_FAST16_FMTd
#define PRIdFAST32  __SPRT_INT_FAST32_FMTd
#define PRIdFAST64  __SPRT_INT_FAST64_FMTd
#define PRIdMAX     __SPRT_INTMAX_FMTd
#define PRIdPTR		__SPRT_INTPTR_FMTd

#define PRIi8		__SPRT_INT8_FMTi
#define PRIi16		__SPRT_INT16_FMTi
#define PRIi32		__SPRT_INT32_FMTi
#define PRIi64		__SPRT_INT64_FMTi
#define PRIiLEAST8  __SPRT_INT_LEAST8_FMTi
#define PRIiLEAST16 __SPRT_INT_LEAST16_FMTi
#define PRIiLEAST32 __SPRT_INT_LEAST32_FMTi
#define PRIiLEAST64 __SPRT_INT_LEAST64_FMTi
#define PRIiFAST8   __SPRT_INT_FAST8_FMTi
#define PRIiFAST16  __SPRT_INT_FAST16_FMTi
#define PRIiFAST32  __SPRT_INT_FAST32_FMTi
#define PRIiFAST64  __SPRT_INT_FAST64_FMTi
#define PRIiMAX     __SPRT_INTMAX_FMTi
#define PRIiPTR		__SPRT_INTPTR_FMTi

#define PRIo8		__SPRT_UINT8_FMTo
#define PRIo16		__SPRT_UINT16_FMTo
#define PRIo32		__SPRT_UINT32_FMTo
#define PRIo64		__SPRT_UINT64_FMTo
#define PRIoLEAST8  __SPRT_UINT_LEAST8_FMTo
#define PRIoLEAST16 __SPRT_UINT_LEAST16_FMTo
#define PRIoLEAST32 __SPRT_UINT_LEAST32_FMTo
#define PRIoLEAST64 __SPRT_UINT_LEAST64_FMTo
#define PRIoFAST8   __SPRT_UINT_FAST8_FMTo
#define PRIoFAST16  __SPRT_UINT_FAST16_FMTo
#define PRIoFAST32  __SPRT_UINT_FAST32_FMTo
#define PRIoFAST64  __SPRT_UINT_FAST64_FMTo
#define PRIoMAX     __SPRT_UINTMAX_FMTo
#define PRIoPTR		__SPRT_UINTPTR_FMTo

#define PRIu8		__SPRT_UINT8_FMTu
#define PRIu16		__SPRT_UINT16_FMTu
#define PRIu32		__SPRT_UINT32_FMTu
#define PRIu64		__SPRT_UINT64_FMTu
#define PRIuLEAST8  __SPRT_UINT_LEAST8_FMTu
#define PRIuLEAST16 __SPRT_UINT_LEAST16_FMTu
#define PRIuLEAST32 __SPRT_UINT_LEAST32_FMTu
#define PRIuLEAST64 __SPRT_UINT_LEAST64_FMTu
#define PRIuFAST8   __SPRT_UINT_FAST8_FMTu
#define PRIuFAST16  __SPRT_UINT_FAST16_FMTu
#define PRIuFAST32  __SPRT_UINT_FAST32_FMTu
#define PRIuFAST64  __SPRT_UINT_FAST64_FMTu
#define PRIuMAX     __SPRT_UINTMAX_FMTu
#define PRIuPTR		__SPRT_UINTPTR_FMTu

#define PRIx8		__SPRT_UINT8_FMTx
#define PRIx16		__SPRT_UINT16_FMTx
#define PRIx32		__SPRT_UINT32_FMTx
#define PRIx64		__SPRT_UINT64_FMTx
#define PRIxLEAST8  __SPRT_UINT_LEAST8_FMTx
#define PRIxLEAST16 __SPRT_UINT_LEAST16_FMTx
#define PRIxLEAST32 __SPRT_UINT_LEAST32_FMTx
#define PRIxLEAST64 __SPRT_UINT_LEAST64_FMTx
#define PRIxFAST8   __SPRT_UINT_FAST8_FMTx
#define PRIxFAST16  __SPRT_UINT_FAST16_FMTx
#define PRIxFAST32  __SPRT_UINT_FAST32_FMTx
#define PRIxFAST64  __SPRT_UINT_FAST64_FMTx
#define PRIxMAX     __SPRT_UINTMAX_FMTx
#define PRIxPTR		__SPRT_UINTPTR_FMTx

#define PRIX8		__SPRT_UINT8_FMTX
#define PRIX16		__SPRT_UINT16_FMTX
#define PRIX32		__SPRT_UINT32_FMTX
#define PRIX64		__SPRT_UINT64_FMTX
#define PRIXLEAST8  __SPRT_UINT_LEAST8_FMTX
#define PRIXLEAST16 __SPRT_UINT_LEAST16_FMTX
#define PRIXLEAST32 __SPRT_UINT_LEAST32_FMTX
#define PRIXLEAST64 __SPRT_UINT_LEAST64_FMTX
#define PRIXFAST8   __SPRT_UINT_FAST8_FMTX
#define PRIXFAST16  __SPRT_UINT_FAST16_FMTX
#define PRIXFAST32  __SPRT_UINT_FAST32_FMTX
#define PRIXFAST64  __SPRT_UINT_FAST64_FMTX
#define PRIXMAX     __SPRT_UINTMAX_FMTX
#define PRIXPTR		__SPRT_UINTPTR_FMTX

#define SCNd8		__SPRT_INT8_FMTd
#define SCNd16		__SPRT_INT16_FMTd
#define SCNd32		__SPRT_INT32_FMTd
#define SCNd64		__SPRT_INT64_FMTd
#define SCNdLEAST8  __SPRT_INT_LEAST8_FMTd
#define SCNdLEAST16 __SPRT_INT_LEAST16_FMTd
#define SCNdLEAST32 __SPRT_INT_LEAST32_FMTd
#define SCNdLEAST64 __SPRT_INT_LEAST64_FMTd
#define SCNdFAST8   __SPRT_INT_FAST8_FMTd
#define SCNdFAST16  __SPRT_INT_FAST16_FMTd
#define SCNdFAST32  __SPRT_INT_FAST32_FMTd
#define SCNdFAST64  __SPRT_INT_FAST64_FMTd
#define SCNdMAX     __SPRT_INTMAX_FMTd
#define SCNdPTR		__SPRT_INTPTR_FMTd

#define SCNi8		__SPRT_INT8_FMTi
#define SCNi16		__SPRT_INT16_FMTi
#define SCNi32		__SPRT_INT32_FMTi
#define SCNi64		__SPRT_INT64_FMTi
#define SCNiLEAST8  __SPRT_INT_LEAST8_FMTi
#define SCNiLEAST16 __SPRT_INT_LEAST16_FMTi
#define SCNiLEAST32 __SPRT_INT_LEAST32_FMTi
#define SCNiLEAST64 __SPRT_INT_LEAST64_FMTi
#define SCNiFAST8   __SPRT_INT_FAST8_FMTi
#define SCNiFAST16  __SPRT_INT_FAST16_FMTi
#define SCNiFAST32  __SPRT_INT_FAST32_FMTi
#define SCNiFAST64  __SPRT_INT_FAST64_FMTi
#define SCNiMAX     __SPRT_INTMAX_FMTi
#define SCNiPTR		__SPRT_INTPTR_FMTi

#define SCNo8		__SPRT_UINT8_FMTo
#define SCNo16		__SPRT_UINT16_FMTo
#define SCNo32		__SPRT_UINT32_FMTo
#define SCNo64		__SPRT_UINT64_FMTo
#define SCNoLEAST8  __SPRT_UINT_LEAST8_FMTo
#define SCNoLEAST16 __SPRT_UINT_LEAST16_FMTo
#define SCNoLEAST32 __SPRT_UINT_LEAST32_FMTo
#define SCNoLEAST64 __SPRT_UINT_LEAST64_FMTo
#define SCNoFAST8   __SPRT_UINT_FAST8_FMTo
#define SCNoFAST16  __SPRT_UINT_FAST16_FMTo
#define SCNoFAST32  __SPRT_UINT_FAST32_FMTo
#define SCNoFAST64  __SPRT_UINT_FAST64_FMTo
#define SCNoMAX     __SPRT_UINTMAX_FMTo
#define SCNoPTR		__SPRT_UINTPTR_FMTo

#define SCNu8		__SPRT_UINT8_FMTu
#define SCNu16		__SPRT_UINT16_FMTu
#define SCNu32		__SPRT_UINT32_FMTu
#define SCNu64		__SPRT_UINT64_FMTu
#define SCNuLEAST8  __SPRT_UINT_LEAST8_FMTu
#define SCNuLEAST16 __SPRT_UINT_LEAST16_FMTu
#define SCNuLEAST32 __SPRT_UINT_LEAST32_FMTu
#define SCNuLEAST64 __SPRT_UINT_LEAST64_FMTu
#define SCNuFAST8   __SPRT_UINT_FAST8_FMTu
#define SCNuFAST16  __SPRT_UINT_FAST16_FMTu
#define SCNuFAST32  __SPRT_UINT_FAST32_FMTu
#define SCNuFAST64  __SPRT_UINT_FAST64_FMTu
#define SCNuMAX     __SPRT_UINTMAX_FMTu
#define SCNuPTR		__SPRT_UINTPTR_FMTu

#define SCNX8		__SPRT_UINT8_FMTX
#define SCNX16		__SPRT_UINT16_FMTX
#define SCNX32		__SPRT_UINT32_FMTX
#define SCNX64		__SPRT_UINT64_FMTX
#define SCNXLEAST8  __SPRT_UINT_LEAST8_FMTX
#define SCNXLEAST16 __SPRT_UINT_LEAST16_FMTX
#define SCNXLEAST32 __SPRT_UINT_LEAST32_FMTX
#define SCNXLEAST64 __SPRT_UINT_LEAST64_FMTX
#define SCNXFAST8   __SPRT_UINT_FAST8_FMTX
#define SCNXFAST16  __SPRT_UINT_FAST16_FMTX
#define SCNXFAST32  __SPRT_UINT_FAST32_FMTX
#define SCNXFAST64  __SPRT_UINT_FAST64_FMTX
#define SCNXMAX     __SPRT_UINTMAX_FMTX
#define SCNXPTR		__SPRT_UINTPTR_FMTX

#endif

#endif // CORE_RUNTIME_INCLUDE_SPRT_WRAPPERS_LIBC_INTTYPES_H_
