#include "dlltable.h"

namespace sprt {

struct UxthemeTable : DllTable {
	UxthemeTable() : DllTable(L"uxtheme.dll", &__uxtheme_begin, &__uxtheme_end) { }

	DllTableRecord __uxtheme_begin;
	SPWIN_DEFINE_PROTO(BeginBufferedAnimation)
	SPWIN_DEFINE_PROTO(BeginBufferedPaint)
	SPWIN_DEFINE_PROTO(BufferedPaintClear)
	SPWIN_DEFINE_PROTO(BufferedPaintInit)
	SPWIN_DEFINE_PROTO(BufferedPaintRenderAnimation)
	SPWIN_DEFINE_PROTO(BufferedPaintSetAlpha)
	SPWIN_DEFINE_PROTO(BufferedPaintStopAllAnimations)
	SPWIN_DEFINE_PROTO(BufferedPaintUnInit)
	SPWIN_DEFINE_PROTO(CloseThemeData)
	SPWIN_DEFINE_PROTO(DrawThemeBackgroundEx)
	SPWIN_DEFINE_PROTO(DrawThemeBackground)
	SPWIN_DEFINE_PROTO(DrawThemeEdge)
	SPWIN_DEFINE_PROTO(DrawThemeIcon)
	SPWIN_DEFINE_PROTO(DrawThemeParentBackground)
	SPWIN_DEFINE_PROTO(DrawThemeText)
	SPWIN_DEFINE_PROTO(DrawThemeTextEx)
	SPWIN_DEFINE_PROTO(EnableThemeDialogTexture)
	SPWIN_DEFINE_PROTO(EnableTheming)
	SPWIN_DEFINE_PROTO(EndBufferedAnimation)
	SPWIN_DEFINE_PROTO(EndBufferedPaint)
	SPWIN_DEFINE_PROTO(OpenThemeDataEx)
	SPWIN_DEFINE_PROTO(GetBufferedPaintBits)
	SPWIN_DEFINE_PROTO(GetBufferedPaintDC)
	SPWIN_DEFINE_PROTO(GetBufferedPaintTargetDC)
	SPWIN_DEFINE_PROTO(GetBufferedPaintTargetRect)
	SPWIN_DEFINE_PROTO(GetCurrentThemeName)
	SPWIN_DEFINE_PROTO(GetThemeAppProperties)
	SPWIN_DEFINE_PROTO(GetThemeBackgroundContentRect)
	SPWIN_DEFINE_PROTO(GetThemeBackgroundExtent)
	SPWIN_DEFINE_PROTO(GetThemeBackgroundRegion)
	SPWIN_DEFINE_PROTO(GetThemeBitmap)
	SPWIN_DEFINE_PROTO(GetThemeBool)
	SPWIN_DEFINE_PROTO(GetThemeColor)
	SPWIN_DEFINE_PROTO(GetThemeDocumentationProperty)
	SPWIN_DEFINE_PROTO(GetThemeEnumValue)
	SPWIN_DEFINE_PROTO(GetThemeFilename)
	SPWIN_DEFINE_PROTO(GetThemeFont)
	SPWIN_DEFINE_PROTO(GetThemeInt)
	SPWIN_DEFINE_PROTO(GetThemeIntList)
	SPWIN_DEFINE_PROTO(GetThemeMargins)
	SPWIN_DEFINE_PROTO(GetThemeMetric)
	SPWIN_DEFINE_PROTO(GetThemePartSize)
	SPWIN_DEFINE_PROTO(GetThemePosition)
	SPWIN_DEFINE_PROTO(GetThemePropertyOrigin)
	SPWIN_DEFINE_PROTO(GetThemeRect)
	SPWIN_DEFINE_PROTO(GetThemeStream)
	SPWIN_DEFINE_PROTO(GetThemeString)
	SPWIN_DEFINE_PROTO(GetThemeSysBool)
	SPWIN_DEFINE_PROTO(GetThemeSysColor)
	SPWIN_DEFINE_PROTO(GetThemeSysColorBrush)
	SPWIN_DEFINE_PROTO(GetThemeSysFont)
	SPWIN_DEFINE_PROTO(GetThemeSysInt)
	SPWIN_DEFINE_PROTO(GetThemeSysSize)
	SPWIN_DEFINE_PROTO(GetThemeSysString)
	SPWIN_DEFINE_PROTO(GetThemeTextExtent)
	SPWIN_DEFINE_PROTO(GetThemeTextMetrics)
	SPWIN_DEFINE_PROTO(GetThemeTransitionDuration)
	SPWIN_DEFINE_PROTO(GetWindowTheme)
	SPWIN_DEFINE_PROTO(HitTestThemeBackground)
	SPWIN_DEFINE_PROTO(IsAppThemed)
	SPWIN_DEFINE_PROTO(IsCompositionActive)
	SPWIN_DEFINE_PROTO(IsThemeActive)
	SPWIN_DEFINE_PROTO(IsThemeBackgroundPartiallyTransparent)
	SPWIN_DEFINE_PROTO(IsThemeDialogTextureEnabled)
	SPWIN_DEFINE_PROTO(IsThemePartDefined)
	SPWIN_DEFINE_PROTO(OpenThemeData)
	SPWIN_DEFINE_PROTO(OpenThemeDataForDpi)
	SPWIN_DEFINE_PROTO(SetThemeAppProperties)
	SPWIN_DEFINE_PROTO(SetWindowTheme)
	SPWIN_DEFINE_PROTO(SetWindowThemeAttribute)
	DllTableRecord __uxtheme_end;
};

} // namespace sprt
