# Copyright (c) 2026 Xenolith Team <admin@xenolith.studio>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

MACOS_SDK_SYSROOT := MacOSX26.1.sdk
TARGET_SYSROOT := sysroot-target
TARGET_TOOLCHAIN_FILE := sysroot-target/toolchain.cmake

TARGET_LIBCXX := $(TARGET_SYSROOT)/usr/lib/libc++.a
TARGET_CLANG_CC := $(TARGET_SYSROOT)/bin/clang
TARGET_CLANG_CXX := $(TARGET_SYSROOT)/bin/clang++

export LIBTOOL=$(abspath $(HOST_LLVM_LIBTOOL))
export LIPO=$(abspath $(HOST_LLVM_LIPO))

$(TARGET_SYSROOT):
	mkdir -p $@
	cp -rf $(MACOS_SDK_SYSROOT)/System $@
	cp -rf $(MACOS_SDK_SYSROOT)/usr $@

$(TARGET_TOOLCHAIN_FILE): $(TARGET_SYSROOT)
	@echo "set(CMAKE_SYSTEM_NAME Darwin)" > $@
	@echo "set(CMAKE_OSX_DEPLOYMENT_TARGET \"14.4\")" >> $@
	@echo "set(CMAKE_OSX_SYSROOT \"$(abspath $(TARGET_SYSROOT))\")" >> $@
	@echo "set(CMAKE_SYSROOT \"$(abspath $(TARGET_SYSROOT))\")" >> $@
	@echo "set(CMAKE_C_COMPILER_TARGET \"$(SP_ARCH_CLANG)\")" >> $@
	@echo "set(CMAKE_CXX_COMPILER_TARGET \"$(SP_ARCH_CLANG)\")" >> $@
	@echo "set(CMAKE_C_FLAGS_INIT \"\")" >> $@
	@echo "set(CMAKE_CXX_FLAGS_INIT \"\")" >> $@
	@echo "set(CMAKE_LINKER_TYPE LLD)" >> $@
	@echo "set(CMAKE_C_COMPILER \"$(abspath $(HOST_TARGET_CLANG_CC))\")" >> $@
	@echo "set(CMAKE_CXX_COMPILER \"$(abspath $(HOST_TARGET_CLANG_CXX))\")" >> $@
	@echo "set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)" >> $@
	@echo "set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)" >> $@
	@echo "set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)" >> $@
	@echo "set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)" >> $@
	@echo "set(CMAKE_LIPO \"$(abspath $(HOST_LLVM_LIPO))\")" >> $@
	@echo "set(CMAKE_LIBTOOL \"$(abspath $(HOST_LLVM_LIBTOOL))\")" >> $@
	@echo "set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG \"-Wl,-rpath,\")" >> $@
	@echo "set(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP \":\")" >> $@
	@echo "set(CMAKE_MACOSX_RPATH TRUE)" >> $@

$(TARGET_LIBCXX): $(HOST_CLANG_CC) $(TARGET_TOOLCHAIN_FILE)
	@echo "Build TARGET_LIBCXX: $(TARGET_LIBCXX)"
	rm -rf build/target-libcxx
	cmake \
		-DCMAKE_TOOLCHAIN_FILE=$(abspath $(TARGET_TOOLCHAIN_FILE)) \
		-G Ninja -S $(LLVM_DIR)/runtimes -B build/target-libcxx \
		-DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind;compiler-rt;" \
		-DLLVM_INSTALL_TOOLCHAIN_ONLY=On \
		-DLLVM_DEFAULT_TARGET_TRIPLE=$(SP_ARCH_CLANG) \
		-DLLVM_ENABLE_PIC=On \
		-DDARWIN_osx_SYSROOT=$(abspath $(MACOS_SDK_SYSROOT)) \
		-DDARWIN_osx_OVERRIDE_SDK_VERSION=\"26.1\" \
		-DDARWIN_macosx_OVERRIDE_SDK_VERSION=\"26.1\" \
		-DDARWIN_osx_ARCHS=arm64 \
		-DDARWIN_osx_BUILTIN_ARCHS=arm64 \
		-DLIBCXX_HAS_ATOMIC_LIB=Off \
		-DLIBCXX_ENABLE_SHARED=Off \
		-DLIBCXX_USE_COMPILER_RT=On \
		-DLIBCXX_INSTALL_LIBRARY_DIR=usr/lib \
		-DLIBCXXABI_USE_LLVM_UNWINDER=On \
		-DLIBCXXABI_USE_COMPILER_RT=On \
		-DLIBCXXABI_ENABLE_STATIC_UNWINDER=On \
		-DLIBCXXABI_ENABLE_SHARED=Off \
		-DLIBCXXABI_INSTALL_LIBRARY_DIR=usr/lib \
		-DLIBUNWIND_USE_COMPILER_RT=On \
		-DLIBUNWIND_ENABLE_SHARED=Off \
		-DLIBUNWIND_INSTALL_LIBRARY_DIR=usr/lib \
		-DCOMPILER_RT_BUILD_BUILTINS=On \
		-DCOMPILER_RT_BUILD_CRT=Off \
		-DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
		-DCOMPILER_RT_BUILD_SANITIZERS=OFF \
		-DCOMPILER_RT_BUILD_XRAY=OFF \
		-DCOMPILER_RT_BUILD_MEMPROF=OFF \
		-DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
		-DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
		-DCOMPILER_RT_USE_LLVM_UNWINDER=ON \
		-DCOMPILER_RT_DEFAULT_TARGET_ARCH=arm64 \
		-DCOMPILER_RT_SCUDO_STANDALONE_SYSROOT_PATH=$(realpath $(TARGET_SYSROOT)) \
		-DCOMPILER_RT_INSTALL_LIBRARY_DIR=$(TARGET_SYSROOT)/usr/lib \
		-DBUILD_SHARED_LIBS=OFF \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_PREFIX=$(TARGET_SYSROOT) \
		-DCMAKE_INSTALL_INCLUDEDIR=usr/include \
		-DCMAKE_INSTALL_LIBDIR=usr/lib \
		-DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
		-DCMAKE_LIPO="$(abspath $(HOST_LLVM_LIPO))"
	cmake --build build/target-libcxx
	cmake --install build/target-libcxx

$(TARGET_CLANG_CC): $(HOST_CLANG_CC) $(TARGET_TOOLCHAIN_FILE) $(TARGET_LIBCXX)
	@echo "Build TARGET_CLANG_CC: $(TARGET_CLANG_CC)"
	rm -rf build/target-llvm
	cmake \
		-DCMAKE_TOOLCHAIN_FILE=$(abspath $(TARGET_TOOLCHAIN_FILE)) \
		-G Ninja -S $(LLVM_DIR)/llvm -B build/target-llvm \
		-DLLVM_ENABLE_PROJECTS="lld;clang" \
		-DLLVM_ENABLE_RUNTIMES="libunwind;compiler-rt" \
		-DLLVM_TARGETS_TO_BUILD="X86;AArch64;WebAssembly" \
		-DLLVM_INSTALL_TOOLCHAIN_ONLY=On \
		-DLLVM_DEFAULT_TARGET_TRIPLE=$(SP_ARCH_CLANG) \
		-DLLVM_ENABLE_PIC=On \
		-DLLVM_LOCAL_RPATH='$$ORIGIN/../lib' \
		-DCLANG_DEFAULT_CXX_STDLIB=libc++ \
		-DCLANG_DEFAULT_RTLIB=compiler-rt \
		-DCLANG_DEFAULT_LINKER=lld \
		-DCLANG_DEFAULT_UNWINDLIB=libunwind \
		-DCLANG_INCLUDE_TESTS=Off \
		-DCLANG_LINK_CLANG_DYLIB=Off \
		-DCLANG_ENABLE_ARCMT=Off \
		-DCLANG_ENABLE_STATIC_ANALYZER=Off \
		-DLIBCLANG_BUILD_STATIC=On \
		-DDARWIN_osx_SYSROOT=$(abspath $(MACOS_SDK_SYSROOT)) \
		-DDARWIN_osx_OVERRIDE_SDK_VERSION=\"26.1\" \
		-DDARWIN_macosx_OVERRIDE_SDK_VERSION=\"26.1\" \
		-DDARWIN_osx_ARCHS=arm64 \
		-DDARWIN_osx_BUILTIN_ARCHS=arm64 \
		-DLIBCXX_HAS_ATOMIC_LIB=Off \
		-DLIBCXX_ENABLE_SHARED=Off \
		-DLIBCXX_USE_COMPILER_RT=On \
		-DLIBCXX_INSTALL_LIBRARY_DIR=usr/lib \
		-DLIBCXXABI_USE_LLVM_UNWINDER=On \
		-DLIBCXXABI_USE_COMPILER_RT=On \
		-DLIBCXXABI_ENABLE_STATIC_UNWINDER=On \
		-DLIBCXXABI_ENABLE_SHARED=Off \
		-DLIBCXXABI_INSTALL_LIBRARY_DIR=usr/lib \
		-DLIBUNWIND_USE_COMPILER_RT=On \
		-DLIBUNWIND_ENABLE_SHARED=Off \
		-DLIBUNWIND_INSTALL_LIBRARY_DIR=usr/lib \
		-DCOMPILER_RT_BUILD_BUILTINS=On \
		-DCOMPILER_RT_BUILD_CRT=Off \
		-DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
		-DCOMPILER_RT_BUILD_SANITIZERS=OFF \
		-DCOMPILER_RT_BUILD_XRAY=OFF \
		-DCOMPILER_RT_BUILD_MEMPROF=OFF \
		-DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
		-DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
		-DCOMPILER_RT_USE_LLVM_UNWINDER=ON \
		-DCOMPILER_RT_DEFAULT_TARGET_ARCH=arm64 \
		-DCOMPILER_RT_SCUDO_STANDALONE_SYSROOT_PATH=$(realpath $(TARGET_SYSROOT)) \
		-DCOMPILER_RT_INSTALL_LIBRARY_DIR=$(TARGET_SYSROOT)/usr/lib \
		-DBUILD_SHARED_LIBS=OFF \
		-DCMAKE_BUILD_TYPE=Release \
		-DCMAKE_INSTALL_RPATH="" \
		-DCMAKE_INSTALL_PREFIX=$(TARGET_SYSROOT) \
		-DCMAKE_INSTALL_INCLUDEDIR=usr/include \
		-DCMAKE_INSTALL_LIBDIR=usr/lib \
		-DCMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
		-DCMAKE_LIPO="$(abspath $(HOST_LLVM_LIPO))" \
		-DCMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG="-Wl,-rpath," \
		-DCMAKE_MACOSX_RPATH=On \
		-DCMAKE_EXE_LINKER_FLAGS="-lc++ -lc++abi" \
		-DCMAKE_SHARED_LINKER_FLAGS="-lc++ -lc++abi"
	cmake --build build/target-llvm
	cmake --install build/target-llvm

target: $(TARGET_TOOLCHAIN_FILE) $(TARGET_CLANG_CC)
