#define __SPRT_SYSCALL_restart_syscall 0
#define __SPRT_SYSCALL_exit 1
#define __SPRT_SYSCALL_fork 2
#define __SPRT_SYSCALL_read 3
#define __SPRT_SYSCALL_write 4
#define __SPRT_SYSCALL_open 5
#define __SPRT_SYSCALL_close 6
#define __SPRT_SYSCALL_waitpid 7
#define __SPRT_SYSCALL_creat 8
#define __SPRT_SYSCALL_link 9
#define __SPRT_SYSCALL_unlink 10
#define __SPRT_SYSCALL_execve 11
#define __SPRT_SYSCALL_chdir 12
#define __SPRT_SYSCALL_time 13
#define __SPRT_SYSCALL_mknod 14
#define __SPRT_SYSCALL_chmod 15
#define __SPRT_SYSCALL_lchown 16
#define __SPRT_SYSCALL_break 17
#define __SPRT_SYSCALL_oldstat 18
#define __SPRT_SYSCALL_lseek 19
#define __SPRT_SYSCALL_getpid 20
#define __SPRT_SYSCALL_mount 21
#define __SPRT_SYSCALL_umount 22
#define __SPRT_SYSCALL_setuid 23
#define __SPRT_SYSCALL_getuid 24
#define __SPRT_SYSCALL_stime 25
#define __SPRT_SYSCALL_ptrace 26
#define __SPRT_SYSCALL_alarm 27
#define __SPRT_SYSCALL_oldfstat 28
#define __SPRT_SYSCALL_pause 29
#define __SPRT_SYSCALL_utime 30
#define __SPRT_SYSCALL_stty 31
#define __SPRT_SYSCALL_gtty 32
#define __SPRT_SYSCALL_access 33
#define __SPRT_SYSCALL_nice 34
#define __SPRT_SYSCALL_ftime 35
#define __SPRT_SYSCALL_sync 36
#define __SPRT_SYSCALL_kill 37
#define __SPRT_SYSCALL_rename 38
#define __SPRT_SYSCALL_mkdir 39
#define __SPRT_SYSCALL_rmdir 40
#define __SPRT_SYSCALL_dup 41
#define __SPRT_SYSCALL_pipe 42
#define __SPRT_SYSCALL_times 43
#define __SPRT_SYSCALL_prof 44
#define __SPRT_SYSCALL_brk 45
#define __SPRT_SYSCALL_setgid 46
#define __SPRT_SYSCALL_getgid 47
#define __SPRT_SYSCALL_signal 48
#define __SPRT_SYSCALL_geteuid 49
#define __SPRT_SYSCALL_getegid 50
#define __SPRT_SYSCALL_acct 51
#define __SPRT_SYSCALL_umount2 52
#define __SPRT_SYSCALL_lock 53
#define __SPRT_SYSCALL_ioctl 54
#define __SPRT_SYSCALL_fcntl 55
#define __SPRT_SYSCALL_mpx 56
#define __SPRT_SYSCALL_setpgid 57
#define __SPRT_SYSCALL_ulimit 58
#define __SPRT_SYSCALL_oldolduname 59
#define __SPRT_SYSCALL_umask 60
#define __SPRT_SYSCALL_chroot 61
#define __SPRT_SYSCALL_ustat 62
#define __SPRT_SYSCALL_dup2 63
#define __SPRT_SYSCALL_getppid 64
#define __SPRT_SYSCALL_getpgrp 65
#define __SPRT_SYSCALL_setsid 66
#define __SPRT_SYSCALL_sigaction 67
#define __SPRT_SYSCALL_sgetmask 68
#define __SPRT_SYSCALL_ssetmask 69
#define __SPRT_SYSCALL_setreuid 70
#define __SPRT_SYSCALL_setregid 71
#define __SPRT_SYSCALL_sigsuspend 72
#define __SPRT_SYSCALL_sigpending 73
#define __SPRT_SYSCALL_sethostname 74
#define __SPRT_SYSCALL_setrlimit 75
#define __SPRT_SYSCALL_getrlimit 76
#define __SPRT_SYSCALL_getrusage 77
#define __SPRT_SYSCALL_gettimeofday 78
#define __SPRT_SYSCALL_settimeofday 79
#define __SPRT_SYSCALL_getgroups 80
#define __SPRT_SYSCALL_setgroups 81
#define __SPRT_SYSCALL_select 82
#define __SPRT_SYSCALL_symlink 83
#define __SPRT_SYSCALL_oldlstat 84
#define __SPRT_SYSCALL_readlink 85
#define __SPRT_SYSCALL_uselib 86
#define __SPRT_SYSCALL_swapon 87
#define __SPRT_SYSCALL_reboot 88
#define __SPRT_SYSCALL_readdir 89
#define __SPRT_SYSCALL_mmap 90
#define __SPRT_SYSCALL_munmap 91
#define __SPRT_SYSCALL_truncate 92
#define __SPRT_SYSCALL_ftruncate 93
#define __SPRT_SYSCALL_fchmod 94
#define __SPRT_SYSCALL_fchown 95
#define __SPRT_SYSCALL_getpriority 96
#define __SPRT_SYSCALL_setpriority 97
#define __SPRT_SYSCALL_profil 98
#define __SPRT_SYSCALL_statfs 99
#define __SPRT_SYSCALL_fstatfs 100
#define __SPRT_SYSCALL_ioperm 101
#define __SPRT_SYSCALL_socketcall 102
#define __SPRT_SYSCALL_syslog 103
#define __SPRT_SYSCALL_setitimer 104
#define __SPRT_SYSCALL_getitimer 105
#define __SPRT_SYSCALL_stat 106
#define __SPRT_SYSCALL_lstat 107
#define __SPRT_SYSCALL_fstat 108
#define __SPRT_SYSCALL_olduname 109
#define __SPRT_SYSCALL_iopl 110
#define __SPRT_SYSCALL_vhangup 111
#define __SPRT_SYSCALL_idle 112
#define __SPRT_SYSCALL_vm86old 113
#define __SPRT_SYSCALL_wait4 114
#define __SPRT_SYSCALL_swapoff 115
#define __SPRT_SYSCALL_sysinfo 116
#define __SPRT_SYSCALL_ipc 117
#define __SPRT_SYSCALL_fsync 118
#define __SPRT_SYSCALL_sigreturn 119
#define __SPRT_SYSCALL_clone 120
#define __SPRT_SYSCALL_setdomainname 121
#define __SPRT_SYSCALL_uname 122
#define __SPRT_SYSCALL_modify_ldt 123
#define __SPRT_SYSCALL_adjtimex 124
#define __SPRT_SYSCALL_mprotect 125
#define __SPRT_SYSCALL_sigprocmask 126
#define __SPRT_SYSCALL_create_module 127
#define __SPRT_SYSCALL_init_module 128
#define __SPRT_SYSCALL_delete_module 129
#define __SPRT_SYSCALL_get_kernel_syms 130
#define __SPRT_SYSCALL_quotactl 131
#define __SPRT_SYSCALL_getpgid 132
#define __SPRT_SYSCALL_fchdir 133
#define __SPRT_SYSCALL_bdflush 134
#define __SPRT_SYSCALL_sysfs 135
#define __SPRT_SYSCALL_personality 136
#define __SPRT_SYSCALL_afs_syscall 137
#define __SPRT_SYSCALL_setfsuid 138
#define __SPRT_SYSCALL_setfsgid 139
#define __SPRT_SYSCALL__llseek 140
#define __SPRT_SYSCALL_getdents 141
#define __SPRT_SYSCALL__newselect 142
#define __SPRT_SYSCALL_flock 143
#define __SPRT_SYSCALL_msync 144
#define __SPRT_SYSCALL_readv 145
#define __SPRT_SYSCALL_writev 146
#define __SPRT_SYSCALL_getsid 147
#define __SPRT_SYSCALL_fdatasync 148
#define __SPRT_SYSCALL__sysctl 149
#define __SPRT_SYSCALL_mlock 150
#define __SPRT_SYSCALL_munlock 151
#define __SPRT_SYSCALL_mlockall 152
#define __SPRT_SYSCALL_munlockall 153
#define __SPRT_SYSCALL_sched_setparam 154
#define __SPRT_SYSCALL_sched_getparam 155
#define __SPRT_SYSCALL_sched_setscheduler 156
#define __SPRT_SYSCALL_sched_getscheduler 157
#define __SPRT_SYSCALL_sched_yield 158
#define __SPRT_SYSCALL_sched_get_priority_max 159
#define __SPRT_SYSCALL_sched_get_priority_min 160
#define __SPRT_SYSCALL_sched_rr_get_interval 161
#define __SPRT_SYSCALL_nanosleep 162
#define __SPRT_SYSCALL_mremap 163
#define __SPRT_SYSCALL_setresuid 164
#define __SPRT_SYSCALL_getresuid 165
#define __SPRT_SYSCALL_vm86 166
#define __SPRT_SYSCALL_query_module 167
#define __SPRT_SYSCALL_poll 168
#define __SPRT_SYSCALL_nfsservctl 169
#define __SPRT_SYSCALL_setresgid 170
#define __SPRT_SYSCALL_getresgid 171
#define __SPRT_SYSCALL_prctl 172
#define __SPRT_SYSCALL_rt_sigreturn 173
#define __SPRT_SYSCALL_rt_sigaction 174
#define __SPRT_SYSCALL_rt_sigprocmask 175
#define __SPRT_SYSCALL_rt_sigpending 176
#define __SPRT_SYSCALL_rt_sigtimedwait 177
#define __SPRT_SYSCALL_rt_sigqueueinfo 178
#define __SPRT_SYSCALL_rt_sigsuspend 179
#define __SPRT_SYSCALL_pread64 180
#define __SPRT_SYSCALL_pwrite64 181
#define __SPRT_SYSCALL_chown 182
#define __SPRT_SYSCALL_getcwd 183
#define __SPRT_SYSCALL_capget 184
#define __SPRT_SYSCALL_capset 185
#define __SPRT_SYSCALL_sigaltstack 186
#define __SPRT_SYSCALL_sendfile 187
#define __SPRT_SYSCALL_getpmsg 188
#define __SPRT_SYSCALL_putpmsg 189
#define __SPRT_SYSCALL_vfork 190
#define __SPRT_SYSCALL_ugetrlimit 191
#define __SPRT_SYSCALL_mmap2 192
#define __SPRT_SYSCALL_truncate64 193
#define __SPRT_SYSCALL_ftruncate64 194
#define __SPRT_SYSCALL_stat64 195
#define __SPRT_SYSCALL_lstat64 196
#define __SPRT_SYSCALL_fstat64 197
#define __SPRT_SYSCALL_lchown32 198
#define __SPRT_SYSCALL_getuid32 199
#define __SPRT_SYSCALL_getgid32 200
#define __SPRT_SYSCALL_geteuid32 201
#define __SPRT_SYSCALL_getegid32 202
#define __SPRT_SYSCALL_setreuid32 203
#define __SPRT_SYSCALL_setregid32 204
#define __SPRT_SYSCALL_getgroups32 205
#define __SPRT_SYSCALL_setgroups32 206
#define __SPRT_SYSCALL_fchown32 207
#define __SPRT_SYSCALL_setresuid32 208
#define __SPRT_SYSCALL_getresuid32 209
#define __SPRT_SYSCALL_setresgid32 210
#define __SPRT_SYSCALL_getresgid32 211
#define __SPRT_SYSCALL_chown32 212
#define __SPRT_SYSCALL_setuid32 213
#define __SPRT_SYSCALL_setgid32 214
#define __SPRT_SYSCALL_setfsuid32 215
#define __SPRT_SYSCALL_setfsgid32 216
#define __SPRT_SYSCALL_pivot_root 217
#define __SPRT_SYSCALL_mincore 218
#define __SPRT_SYSCALL_madvise 219
#define __SPRT_SYSCALL_getdents64 220
#define __SPRT_SYSCALL_fcntl64 221
#define __SPRT_SYSCALL_gettid 224
#define __SPRT_SYSCALL_readahead 225
#define __SPRT_SYSCALL_setxattr 226
#define __SPRT_SYSCALL_lsetxattr 227
#define __SPRT_SYSCALL_fsetxattr 228
#define __SPRT_SYSCALL_getxattr 229
#define __SPRT_SYSCALL_lgetxattr 230
#define __SPRT_SYSCALL_fgetxattr 231
#define __SPRT_SYSCALL_listxattr 232
#define __SPRT_SYSCALL_llistxattr 233
#define __SPRT_SYSCALL_flistxattr 234
#define __SPRT_SYSCALL_removexattr 235
#define __SPRT_SYSCALL_lremovexattr 236
#define __SPRT_SYSCALL_fremovexattr 237
#define __SPRT_SYSCALL_tkill 238
#define __SPRT_SYSCALL_sendfile64 239
#define __SPRT_SYSCALL_futex 240
#define __SPRT_SYSCALL_sched_setaffinity 241
#define __SPRT_SYSCALL_sched_getaffinity 242
#define __SPRT_SYSCALL_set_thread_area 243
#define __SPRT_SYSCALL_get_thread_area 244
#define __SPRT_SYSCALL_io_setup 245
#define __SPRT_SYSCALL_io_destroy 246
#define __SPRT_SYSCALL_io_getevents 247
#define __SPRT_SYSCALL_io_submit 248
#define __SPRT_SYSCALL_io_cancel 249
#define __SPRT_SYSCALL_fadvise64 250
#define __SPRT_SYSCALL_exit_group 252
#define __SPRT_SYSCALL_lookup_dcookie 253
#define __SPRT_SYSCALL_epoll_create 254
#define __SPRT_SYSCALL_epoll_ctl 255
#define __SPRT_SYSCALL_epoll_wait 256
#define __SPRT_SYSCALL_remap_file_pages 257
#define __SPRT_SYSCALL_set_tid_address 258
#define __SPRT_SYSCALL_timer_create 259
#define __SPRT_SYSCALL_timer_settime 260
#define __SPRT_SYSCALL_timer_gettime 261
#define __SPRT_SYSCALL_timer_getoverrun 262
#define __SPRT_SYSCALL_timer_delete 263
#define __SPRT_SYSCALL_clock_settime 264
#define __SPRT_SYSCALL_clock_gettime 265
#define __SPRT_SYSCALL_clock_getres 266
#define __SPRT_SYSCALL_clock_nanosleep 267
#define __SPRT_SYSCALL_statfs64 268
#define __SPRT_SYSCALL_fstatfs64 269
#define __SPRT_SYSCALL_tgkill 270
#define __SPRT_SYSCALL_utimes 271
#define __SPRT_SYSCALL_fadvise64_64 272
#define __SPRT_SYSCALL_vserver 273
#define __SPRT_SYSCALL_mbind 274
#define __SPRT_SYSCALL_get_mempolicy 275
#define __SPRT_SYSCALL_set_mempolicy 276
#define __SPRT_SYSCALL_mq_open 277
#define __SPRT_SYSCALL_mq_unlink 278
#define __SPRT_SYSCALL_mq_timedsend 279
#define __SPRT_SYSCALL_mq_timedreceive 280
#define __SPRT_SYSCALL_mq_notify 281
#define __SPRT_SYSCALL_mq_getsetattr 282
#define __SPRT_SYSCALL_kexec_load 283
#define __SPRT_SYSCALL_waitid 284
#define __SPRT_SYSCALL_add_key 286
#define __SPRT_SYSCALL_request_key 287
#define __SPRT_SYSCALL_keyctl 288
#define __SPRT_SYSCALL_ioprio_set 289
#define __SPRT_SYSCALL_ioprio_get 290
#define __SPRT_SYSCALL_inotify_init 291
#define __SPRT_SYSCALL_inotify_add_watch 292
#define __SPRT_SYSCALL_inotify_rm_watch 293
#define __SPRT_SYSCALL_migrate_pages 294
#define __SPRT_SYSCALL_openat 295
#define __SPRT_SYSCALL_mkdirat 296
#define __SPRT_SYSCALL_mknodat 297
#define __SPRT_SYSCALL_fchownat 298
#define __SPRT_SYSCALL_futimesat 299
#define __SPRT_SYSCALL_fstatat64 300
#define __SPRT_SYSCALL_unlinkat 301
#define __SPRT_SYSCALL_renameat 302
#define __SPRT_SYSCALL_linkat 303
#define __SPRT_SYSCALL_symlinkat 304
#define __SPRT_SYSCALL_readlinkat 305
#define __SPRT_SYSCALL_fchmodat 306
#define __SPRT_SYSCALL_faccessat 307
#define __SPRT_SYSCALL_pselect6 308
#define __SPRT_SYSCALL_ppoll 309
#define __SPRT_SYSCALL_unshare 310
#define __SPRT_SYSCALL_set_robust_list 311
#define __SPRT_SYSCALL_get_robust_list 312
#define __SPRT_SYSCALL_splice 313
#define __SPRT_SYSCALL_sync_file_range 314
#define __SPRT_SYSCALL_tee 315
#define __SPRT_SYSCALL_vmsplice 316
#define __SPRT_SYSCALL_move_pages 317
#define __SPRT_SYSCALL_getcpu 318
#define __SPRT_SYSCALL_epoll_pwait 319
#define __SPRT_SYSCALL_utimensat 320
#define __SPRT_SYSCALL_signalfd 321
#define __SPRT_SYSCALL_timerfd_create 322
#define __SPRT_SYSCALL_eventfd 323
#define __SPRT_SYSCALL_fallocate 324
#define __SPRT_SYSCALL_timerfd_settime 325
#define __SPRT_SYSCALL_timerfd_gettime 326
#define __SPRT_SYSCALL_signalfd4 327
#define __SPRT_SYSCALL_eventfd2 328
#define __SPRT_SYSCALL_epoll_create1 329
#define __SPRT_SYSCALL_dup3 330
#define __SPRT_SYSCALL_pipe2 331
#define __SPRT_SYSCALL_inotify_init1 332
#define __SPRT_SYSCALL_preadv 333
#define __SPRT_SYSCALL_pwritev 334
#define __SPRT_SYSCALL_rt_tgsigqueueinfo 335
#define __SPRT_SYSCALL_perf_event_open 336
#define __SPRT_SYSCALL_recvmmsg 337
#define __SPRT_SYSCALL_fanotify_init 338
#define __SPRT_SYSCALL_fanotify_mark 339
#define __SPRT_SYSCALL_prlimit64 340
#define __SPRT_SYSCALL_name_to_handle_at 341
#define __SPRT_SYSCALL_open_by_handle_at 342
#define __SPRT_SYSCALL_clock_adjtime 343
#define __SPRT_SYSCALL_syncfs 344
#define __SPRT_SYSCALL_sendmmsg 345
#define __SPRT_SYSCALL_setns 346
#define __SPRT_SYSCALL_process_vm_readv 347
#define __SPRT_SYSCALL_process_vm_writev 348
#define __SPRT_SYSCALL_kcmp 349
#define __SPRT_SYSCALL_finit_module 350
#define __SPRT_SYSCALL_sched_setattr 351
#define __SPRT_SYSCALL_sched_getattr 352
#define __SPRT_SYSCALL_renameat2 353
#define __SPRT_SYSCALL_seccomp 354
#define __SPRT_SYSCALL_getrandom 355
#define __SPRT_SYSCALL_memfd_create 356
#define __SPRT_SYSCALL_bpf 357
#define __SPRT_SYSCALL_execveat 358
#define __SPRT_SYSCALL_socket 359
#define __SPRT_SYSCALL_socketpair 360
#define __SPRT_SYSCALL_bind 361
#define __SPRT_SYSCALL_connect 362
#define __SPRT_SYSCALL_listen 363
#define __SPRT_SYSCALL_accept4 364
#define __SPRT_SYSCALL_getsockopt 365
#define __SPRT_SYSCALL_setsockopt 366
#define __SPRT_SYSCALL_getsockname 367
#define __SPRT_SYSCALL_getpeername 368
#define __SPRT_SYSCALL_sendto 369
#define __SPRT_SYSCALL_sendmsg 370
#define __SPRT_SYSCALL_recvfrom 371
#define __SPRT_SYSCALL_recvmsg 372
#define __SPRT_SYSCALL_shutdown 373
#define __SPRT_SYSCALL_userfaultfd 374
#define __SPRT_SYSCALL_membarrier 375
#define __SPRT_SYSCALL_mlock2 376
#define __SPRT_SYSCALL_copy_file_range 377
#define __SPRT_SYSCALL_preadv2 378
#define __SPRT_SYSCALL_pwritev2 379
#define __SPRT_SYSCALL_pkey_mprotect 380
#define __SPRT_SYSCALL_pkey_alloc 381
#define __SPRT_SYSCALL_pkey_free 382
#define __SPRT_SYSCALL_statx 383
#define __SPRT_SYSCALL_arch_prctl 384
#define __SPRT_SYSCALL_io_pgetevents 385
#define __SPRT_SYSCALL_rseq 386
#define __SPRT_SYSCALL_semget 393
#define __SPRT_SYSCALL_semctl 394
#define __SPRT_SYSCALL_shmget 395
#define __SPRT_SYSCALL_shmctl 396
#define __SPRT_SYSCALL_shmat 397
#define __SPRT_SYSCALL_shmdt 398
#define __SPRT_SYSCALL_msgget 399
#define __SPRT_SYSCALL_msgsnd 400
#define __SPRT_SYSCALL_msgrcv 401
#define __SPRT_SYSCALL_msgctl 402
#define __SPRT_SYSCALL_clock_gettime64 403
#define __SPRT_SYSCALL_clock_settime64 404
#define __SPRT_SYSCALL_clock_adjtime64 405
#define __SPRT_SYSCALL_clock_getres_time64 406
#define __SPRT_SYSCALL_clock_nanosleep_time64 407
#define __SPRT_SYSCALL_timer_gettime64 408
#define __SPRT_SYSCALL_timer_settime64 409
#define __SPRT_SYSCALL_timerfd_gettime64 410
#define __SPRT_SYSCALL_timerfd_settime64 411
#define __SPRT_SYSCALL_utimensat_time64 412
#define __SPRT_SYSCALL_pselect6_time64 413
#define __SPRT_SYSCALL_ppoll_time64 414
#define __SPRT_SYSCALL_io_pgetevents_time64 416
#define __SPRT_SYSCALL_recvmmsg_time64 417
#define __SPRT_SYSCALL_mq_timedsend_time64 418
#define __SPRT_SYSCALL_mq_timedreceive_time64 419
#define __SPRT_SYSCALL_semtimedop_time64 420
#define __SPRT_SYSCALL_rt_sigtimedwait_time64 421
#define __SPRT_SYSCALL_futex_time64 422
#define __SPRT_SYSCALL_sched_rr_get_interval_time64 423
#define __SPRT_SYSCALL_pidfd_send_signal 424
#define __SPRT_SYSCALL_io_uring_setup 425
#define __SPRT_SYSCALL_io_uring_enter 426
#define __SPRT_SYSCALL_io_uring_register 427
#define __SPRT_SYSCALL_open_tree 428
#define __SPRT_SYSCALL_move_mount 429
#define __SPRT_SYSCALL_fsopen 430
#define __SPRT_SYSCALL_fsconfig 431
#define __SPRT_SYSCALL_fsmount 432
#define __SPRT_SYSCALL_fspick 433
#define __SPRT_SYSCALL_pidfd_open 434
#define __SPRT_SYSCALL_clone3 435
#define __SPRT_SYSCALL_close_range 436
#define __SPRT_SYSCALL_openat2 437
#define __SPRT_SYSCALL_pidfd_getfd 438
#define __SPRT_SYSCALL_faccessat2 439
#define __SPRT_SYSCALL_process_madvise 440
#define __SPRT_SYSCALL_epoll_pwait2 441
#define __SPRT_SYSCALL_mount_setattr 442
#define __SPRT_SYSCALL_quotactl_fd 443
#define __SPRT_SYSCALL_landlock_create_ruleset 444
#define __SPRT_SYSCALL_landlock_add_rule 445
#define __SPRT_SYSCALL_landlock_restrict_self 446
#define __SPRT_SYSCALL_memfd_secret 447
#define __SPRT_SYSCALL_process_mrelease 448
#define __SPRT_SYSCALL_futex_waitv 449
#define __SPRT_SYSCALL_set_mempolicy_home_node 450
#define __SPRT_SYSCALL_cachestat 451
#define __SPRT_SYSCALL_fchmodat2 452
#define __SPRT_SYSCALL_map_shadow_stack 453
#define __SPRT_SYSCALL_futex_wake 454
#define __SPRT_SYSCALL_futex_wait 455
#define __SPRT_SYSCALL_futex_requeue 456
#define __SPRT_SYSCALL_statmount 457
#define __SPRT_SYSCALL_listmount 458
#define __SPRT_SYSCALL_lsm_get_self_attr 459
#define __SPRT_SYSCALL_lsm_set_self_attr 460
#define __SPRT_SYSCALL_lsm_list_modules 461
#define __SPRT_SYSCALL_mseal 462
#define __SPRT_SYSCALL_setxattrat 463
#define __SPRT_SYSCALL_getxattrat 464
#define __SPRT_SYSCALL_listxattrat 465
#define __SPRT_SYSCALL_removexattrat 466
#define __SPRT_SYSCALL_open_tree_attr 467
#define __SPRT_SYSCALL_file_getattr 468
#define __SPRT_SYSCALL_file_setattr 469
