#define __SPRT_SIGHUP    1
#define __SPRT_SIGINT    2
#define __SPRT_SIGQUIT   3
#define __SPRT_SIGILL    4
#define __SPRT_SIGTRAP   5
#define __SPRT_SIGABRT   6
#define __SPRT_SIGIOT    __SPRT_SIGABRT
#define __SPRT_SIGBUS    7
#define __SPRT_SIGFPE    8
#define __SPRT_SIGKILL   9
#define __SPRT_SIGUSR1   10
#define __SPRT_SIGSEGV   11
#define __SPRT_SIGUSR2   12
#define __SPRT_SIGPIPE   13
#define __SPRT_SIGALRM   14
#define __SPRT_SIGTERM   15
#define __SPRT_SIGSTKFLT 16
#define __SPRT_SIGCHLD   17
#define __SPRT_SIGCONT   18
#define __SPRT_SIGSTOP   19
#define __SPRT_SIGTSTP   20
#define __SPRT_SIGTTIN   21
#define __SPRT_SIGTTOU   22
#define __SPRT_SIGURG    23
#define __SPRT_SIGXCPU   24
#define __SPRT_SIGXFSZ   25
#define __SPRT_SIGVTALRM 26
#define __SPRT_SIGPROF   27
#define __SPRT_SIGWINCH  28
#define __SPRT_SIGIO     29
#define __SPRT_SIGPOLL   29
#define __SPRT_SIGPWR    30
#define __SPRT_SIGSYS    31
#define __SPRT_SIGUNUSED __SPRT_SIGSYS

#define __SPRT__NSIG 65
