#define __SPRT_SYSCALL_restart_syscall 0
#define __SPRT_SYSCALL_exit 1
#define __SPRT_SYSCALL_fork 2
#define __SPRT_SYSCALL_read 3
#define __SPRT_SYSCALL_write 4
#define __SPRT_SYSCALL_open 5
#define __SPRT_SYSCALL_close 6
#define __SPRT_SYSCALL_creat 8
#define __SPRT_SYSCALL_link 9
#define __SPRT_SYSCALL_unlink 10
#define __SPRT_SYSCALL_execve 11
#define __SPRT_SYSCALL_chdir 12
#define __SPRT_SYSCALL_mknod 14
#define __SPRT_SYSCALL_chmod 15
#define __SPRT_SYSCALL_lchown 16
#define __SPRT_SYSCALL_lseek 19
#define __SPRT_SYSCALL_getpid 20
#define __SPRT_SYSCALL_mount 21
#define __SPRT_SYSCALL_setuid 23
#define __SPRT_SYSCALL_getuid 24
#define __SPRT_SYSCALL_ptrace 26
#define __SPRT_SYSCALL_pause 29
#define __SPRT_SYSCALL_access 33
#define __SPRT_SYSCALL_nice 34
#define __SPRT_SYSCALL_sync 36
#define __SPRT_SYSCALL_kill 37
#define __SPRT_SYSCALL_rename 38
#define __SPRT_SYSCALL_mkdir 39
#define __SPRT_SYSCALL_rmdir 40
#define __SPRT_SYSCALL_dup 41
#define __SPRT_SYSCALL_pipe 42
#define __SPRT_SYSCALL_times 43
#define __SPRT_SYSCALL_brk 45
#define __SPRT_SYSCALL_setgid 46
#define __SPRT_SYSCALL_getgid 47
#define __SPRT_SYSCALL_geteuid 49
#define __SPRT_SYSCALL_getegid 50
#define __SPRT_SYSCALL_acct 51
#define __SPRT_SYSCALL_umount2 52
#define __SPRT_SYSCALL_ioctl 54
#define __SPRT_SYSCALL_fcntl 55
#define __SPRT_SYSCALL_setpgid 57
#define __SPRT_SYSCALL_umask 60
#define __SPRT_SYSCALL_chroot 61
#define __SPRT_SYSCALL_ustat 62
#define __SPRT_SYSCALL_dup2 63
#define __SPRT_SYSCALL_getppid 64
#define __SPRT_SYSCALL_getpgrp 65
#define __SPRT_SYSCALL_setsid 66
#define __SPRT_SYSCALL_sigaction 67
#define __SPRT_SYSCALL_setreuid 70
#define __SPRT_SYSCALL_setregid 71
#define __SPRT_SYSCALL_sigsuspend 72
#define __SPRT_SYSCALL_sigpending 73
#define __SPRT_SYSCALL_sethostname 74
#define __SPRT_SYSCALL_setrlimit 75
#define __SPRT_SYSCALL_getrusage 77
#define __SPRT_SYSCALL_gettimeofday 78
#define __SPRT_SYSCALL_settimeofday 79
#define __SPRT_SYSCALL_getgroups 80
#define __SPRT_SYSCALL_setgroups 81
#define __SPRT_SYSCALL_symlink 83
#define __SPRT_SYSCALL_readlink 85
#define __SPRT_SYSCALL_uselib 86
#define __SPRT_SYSCALL_swapon 87
#define __SPRT_SYSCALL_reboot 88
#define __SPRT_SYSCALL_munmap 91
#define __SPRT_SYSCALL_truncate 92
#define __SPRT_SYSCALL_ftruncate 93
#define __SPRT_SYSCALL_fchmod 94
#define __SPRT_SYSCALL_fchown 95
#define __SPRT_SYSCALL_getpriority 96
#define __SPRT_SYSCALL_setpriority 97
#define __SPRT_SYSCALL_statfs 99
#define __SPRT_SYSCALL_fstatfs 100
#define __SPRT_SYSCALL_syslog 103
#define __SPRT_SYSCALL_setitimer 104
#define __SPRT_SYSCALL_getitimer 105
#define __SPRT_SYSCALL_stat 106
#define __SPRT_SYSCALL_lstat 107
#define __SPRT_SYSCALL_fstat 108
#define __SPRT_SYSCALL_vhangup 111
#define __SPRT_SYSCALL_wait4 114
#define __SPRT_SYSCALL_swapoff 115
#define __SPRT_SYSCALL_sysinfo 116
#define __SPRT_SYSCALL_fsync 118
#define __SPRT_SYSCALL_sigreturn 119
#define __SPRT_SYSCALL_clone 120
#define __SPRT_SYSCALL_setdomainname 121
#define __SPRT_SYSCALL_uname 122
#define __SPRT_SYSCALL_adjtimex 124
#define __SPRT_SYSCALL_mprotect 125
#define __SPRT_SYSCALL_sigprocmask 126
#define __SPRT_SYSCALL_init_module 128
#define __SPRT_SYSCALL_delete_module 129
#define __SPRT_SYSCALL_quotactl 131
#define __SPRT_SYSCALL_getpgid 132
#define __SPRT_SYSCALL_fchdir 133
#define __SPRT_SYSCALL_bdflush 134
#define __SPRT_SYSCALL_sysfs 135
#define __SPRT_SYSCALL_personality 136
#define __SPRT_SYSCALL_setfsuid 138
#define __SPRT_SYSCALL_setfsgid 139
#define __SPRT_SYSCALL__llseek 140
#define __SPRT_SYSCALL_getdents 141
#define __SPRT_SYSCALL__newselect 142
#define __SPRT_SYSCALL_flock 143
#define __SPRT_SYSCALL_msync 144
#define __SPRT_SYSCALL_readv 145
#define __SPRT_SYSCALL_writev 146
#define __SPRT_SYSCALL_getsid 147
#define __SPRT_SYSCALL_fdatasync 148
#define __SPRT_SYSCALL__sysctl 149
#define __SPRT_SYSCALL_mlock 150
#define __SPRT_SYSCALL_munlock 151
#define __SPRT_SYSCALL_mlockall 152
#define __SPRT_SYSCALL_munlockall 153
#define __SPRT_SYSCALL_sched_setparam 154
#define __SPRT_SYSCALL_sched_getparam 155
#define __SPRT_SYSCALL_sched_setscheduler 156
#define __SPRT_SYSCALL_sched_getscheduler 157
#define __SPRT_SYSCALL_sched_yield 158
#define __SPRT_SYSCALL_sched_get_priority_max 159
#define __SPRT_SYSCALL_sched_get_priority_min 160
#define __SPRT_SYSCALL_sched_rr_get_interval 161
#define __SPRT_SYSCALL_nanosleep 162
#define __SPRT_SYSCALL_mremap 163
#define __SPRT_SYSCALL_setresuid 164
#define __SPRT_SYSCALL_getresuid 165
#define __SPRT_SYSCALL_poll 168
#define __SPRT_SYSCALL_nfsservctl 169
#define __SPRT_SYSCALL_setresgid 170
#define __SPRT_SYSCALL_getresgid 171
#define __SPRT_SYSCALL_prctl 172
#define __SPRT_SYSCALL_rt_sigreturn 173
#define __SPRT_SYSCALL_rt_sigaction 174
#define __SPRT_SYSCALL_rt_sigprocmask 175
#define __SPRT_SYSCALL_rt_sigpending 176
#define __SPRT_SYSCALL_rt_sigtimedwait 177
#define __SPRT_SYSCALL_rt_sigqueueinfo 178
#define __SPRT_SYSCALL_rt_sigsuspend 179
#define __SPRT_SYSCALL_pread64 180
#define __SPRT_SYSCALL_pwrite64 181
#define __SPRT_SYSCALL_chown 182
#define __SPRT_SYSCALL_getcwd 183
#define __SPRT_SYSCALL_capget 184
#define __SPRT_SYSCALL_capset 185
#define __SPRT_SYSCALL_sigaltstack 186
#define __SPRT_SYSCALL_sendfile 187
#define __SPRT_SYSCALL_vfork 190
#define __SPRT_SYSCALL_ugetrlimit 191
#define __SPRT_SYSCALL_mmap2 192
#define __SPRT_SYSCALL_truncate64 193
#define __SPRT_SYSCALL_ftruncate64 194
#define __SPRT_SYSCALL_stat64 195
#define __SPRT_SYSCALL_lstat64 196
#define __SPRT_SYSCALL_fstat64 197
#define __SPRT_SYSCALL_lchown32 198
#define __SPRT_SYSCALL_getuid32 199
#define __SPRT_SYSCALL_getgid32 200
#define __SPRT_SYSCALL_geteuid32 201
#define __SPRT_SYSCALL_getegid32 202
#define __SPRT_SYSCALL_setreuid32 203
#define __SPRT_SYSCALL_setregid32 204
#define __SPRT_SYSCALL_getgroups32 205
#define __SPRT_SYSCALL_setgroups32 206
#define __SPRT_SYSCALL_fchown32 207
#define __SPRT_SYSCALL_setresuid32 208
#define __SPRT_SYSCALL_getresuid32 209
#define __SPRT_SYSCALL_setresgid32 210
#define __SPRT_SYSCALL_getresgid32 211
#define __SPRT_SYSCALL_chown32 212
#define __SPRT_SYSCALL_setuid32 213
#define __SPRT_SYSCALL_setgid32 214
#define __SPRT_SYSCALL_setfsuid32 215
#define __SPRT_SYSCALL_setfsgid32 216
#define __SPRT_SYSCALL_getdents64 217
#define __SPRT_SYSCALL_pivot_root 218
#define __SPRT_SYSCALL_mincore 219
#define __SPRT_SYSCALL_madvise 220
#define __SPRT_SYSCALL_fcntl64 221
#define __SPRT_SYSCALL_gettid 224
#define __SPRT_SYSCALL_readahead 225
#define __SPRT_SYSCALL_setxattr 226
#define __SPRT_SYSCALL_lsetxattr 227
#define __SPRT_SYSCALL_fsetxattr 228
#define __SPRT_SYSCALL_getxattr 229
#define __SPRT_SYSCALL_lgetxattr 230
#define __SPRT_SYSCALL_fgetxattr 231
#define __SPRT_SYSCALL_listxattr 232
#define __SPRT_SYSCALL_llistxattr 233
#define __SPRT_SYSCALL_flistxattr 234
#define __SPRT_SYSCALL_removexattr 235
#define __SPRT_SYSCALL_lremovexattr 236
#define __SPRT_SYSCALL_fremovexattr 237
#define __SPRT_SYSCALL_tkill 238
#define __SPRT_SYSCALL_sendfile64 239
#define __SPRT_SYSCALL_futex 240
#define __SPRT_SYSCALL_sched_setaffinity 241
#define __SPRT_SYSCALL_sched_getaffinity 242
#define __SPRT_SYSCALL_io_setup 243
#define __SPRT_SYSCALL_io_destroy 244
#define __SPRT_SYSCALL_io_getevents 245
#define __SPRT_SYSCALL_io_submit 246
#define __SPRT_SYSCALL_io_cancel 247
#define __SPRT_SYSCALL_exit_group 248
#define __SPRT_SYSCALL_lookup_dcookie 249
#define __SPRT_SYSCALL_epoll_create 250
#define __SPRT_SYSCALL_epoll_ctl 251
#define __SPRT_SYSCALL_epoll_wait 252
#define __SPRT_SYSCALL_remap_file_pages 253
#define __SPRT_SYSCALL_set_tid_address 256
#define __SPRT_SYSCALL_timer_create 257
#define __SPRT_SYSCALL_timer_settime 258
#define __SPRT_SYSCALL_timer_gettime 259
#define __SPRT_SYSCALL_timer_getoverrun 260
#define __SPRT_SYSCALL_timer_delete 261
#define __SPRT_SYSCALL_clock_settime 262
#define __SPRT_SYSCALL_clock_gettime 263
#define __SPRT_SYSCALL_clock_getres 264
#define __SPRT_SYSCALL_clock_nanosleep 265
#define __SPRT_SYSCALL_statfs64 266
#define __SPRT_SYSCALL_fstatfs64 267
#define __SPRT_SYSCALL_tgkill 268
#define __SPRT_SYSCALL_utimes 269
#define __SPRT_SYSCALL_arm_fadvise64_64 270
#define __SPRT_SYSCALL_pciconfig_iobase 271
#define __SPRT_SYSCALL_pciconfig_read 272
#define __SPRT_SYSCALL_pciconfig_write 273
#define __SPRT_SYSCALL_mq_open 274
#define __SPRT_SYSCALL_mq_unlink 275
#define __SPRT_SYSCALL_mq_timedsend 276
#define __SPRT_SYSCALL_mq_timedreceive 277
#define __SPRT_SYSCALL_mq_notify 278
#define __SPRT_SYSCALL_mq_getsetattr 279
#define __SPRT_SYSCALL_waitid 280
#define __SPRT_SYSCALL_socket 281
#define __SPRT_SYSCALL_bind 282
#define __SPRT_SYSCALL_connect 283
#define __SPRT_SYSCALL_listen 284
#define __SPRT_SYSCALL_accept 285
#define __SPRT_SYSCALL_getsockname 286
#define __SPRT_SYSCALL_getpeername 287
#define __SPRT_SYSCALL_socketpair 288
#define __SPRT_SYSCALL_send 289
#define __SPRT_SYSCALL_sendto 290
#define __SPRT_SYSCALL_recv 291
#define __SPRT_SYSCALL_recvfrom 292
#define __SPRT_SYSCALL_shutdown 293
#define __SPRT_SYSCALL_setsockopt 294
#define __SPRT_SYSCALL_getsockopt 295
#define __SPRT_SYSCALL_sendmsg 296
#define __SPRT_SYSCALL_recvmsg 297
#define __SPRT_SYSCALL_semop 298
#define __SPRT_SYSCALL_semget 299
#define __SPRT_SYSCALL_semctl 300
#define __SPRT_SYSCALL_msgsnd 301
#define __SPRT_SYSCALL_msgrcv 302
#define __SPRT_SYSCALL_msgget 303
#define __SPRT_SYSCALL_msgctl 304
#define __SPRT_SYSCALL_shmat 305
#define __SPRT_SYSCALL_shmdt 306
#define __SPRT_SYSCALL_shmget 307
#define __SPRT_SYSCALL_shmctl 308
#define __SPRT_SYSCALL_add_key 309
#define __SPRT_SYSCALL_request_key 310
#define __SPRT_SYSCALL_keyctl 311
#define __SPRT_SYSCALL_semtimedop 312
#define __SPRT_SYSCALL_vserver 313
#define __SPRT_SYSCALL_ioprio_set 314
#define __SPRT_SYSCALL_ioprio_get 315
#define __SPRT_SYSCALL_inotify_init 316
#define __SPRT_SYSCALL_inotify_add_watch 317
#define __SPRT_SYSCALL_inotify_rm_watch 318
#define __SPRT_SYSCALL_mbind 319
#define __SPRT_SYSCALL_get_mempolicy 320
#define __SPRT_SYSCALL_set_mempolicy 321
#define __SPRT_SYSCALL_openat 322
#define __SPRT_SYSCALL_mkdirat 323
#define __SPRT_SYSCALL_mknodat 324
#define __SPRT_SYSCALL_fchownat 325
#define __SPRT_SYSCALL_futimesat 326
#define __SPRT_SYSCALL_fstatat64 327
#define __SPRT_SYSCALL_unlinkat 328
#define __SPRT_SYSCALL_renameat 329
#define __SPRT_SYSCALL_linkat 330
#define __SPRT_SYSCALL_symlinkat 331
#define __SPRT_SYSCALL_readlinkat 332
#define __SPRT_SYSCALL_fchmodat 333
#define __SPRT_SYSCALL_faccessat 334
#define __SPRT_SYSCALL_pselect6 335
#define __SPRT_SYSCALL_ppoll 336
#define __SPRT_SYSCALL_unshare 337
#define __SPRT_SYSCALL_set_robust_list 338
#define __SPRT_SYSCALL_get_robust_list 339
#define __SPRT_SYSCALL_splice 340
#define __SPRT_SYSCALL_arm_sync_file_range 341
#define __SPRT_SYSCALL_tee 342
#define __SPRT_SYSCALL_vmsplice 343
#define __SPRT_SYSCALL_move_pages 344
#define __SPRT_SYSCALL_getcpu 345
#define __SPRT_SYSCALL_epoll_pwait 346
#define __SPRT_SYSCALL_kexec_load 347
#define __SPRT_SYSCALL_utimensat 348
#define __SPRT_SYSCALL_signalfd 349
#define __SPRT_SYSCALL_timerfd_create 350
#define __SPRT_SYSCALL_eventfd 351
#define __SPRT_SYSCALL_fallocate 352
#define __SPRT_SYSCALL_timerfd_settime 353
#define __SPRT_SYSCALL_timerfd_gettime 354
#define __SPRT_SYSCALL_signalfd4 355
#define __SPRT_SYSCALL_eventfd2 356
#define __SPRT_SYSCALL_epoll_create1 357
#define __SPRT_SYSCALL_dup3 358
#define __SPRT_SYSCALL_pipe2 359
#define __SPRT_SYSCALL_inotify_init1 360
#define __SPRT_SYSCALL_preadv 361
#define __SPRT_SYSCALL_pwritev 362
#define __SPRT_SYSCALL_rt_tgsigqueueinfo 363
#define __SPRT_SYSCALL_perf_event_open 364
#define __SPRT_SYSCALL_recvmmsg 365
#define __SPRT_SYSCALL_accept4 366
#define __SPRT_SYSCALL_fanotify_init 367
#define __SPRT_SYSCALL_fanotify_mark 368
#define __SPRT_SYSCALL_prlimit64 369
#define __SPRT_SYSCALL_name_to_handle_at 370
#define __SPRT_SYSCALL_open_by_handle_at 371
#define __SPRT_SYSCALL_clock_adjtime 372
#define __SPRT_SYSCALL_syncfs 373
#define __SPRT_SYSCALL_sendmmsg 374
#define __SPRT_SYSCALL_setns 375
#define __SPRT_SYSCALL_process_vm_readv 376
#define __SPRT_SYSCALL_process_vm_writev 377
#define __SPRT_SYSCALL_kcmp 378
#define __SPRT_SYSCALL_finit_module 379
#define __SPRT_SYSCALL_sched_setattr 380
#define __SPRT_SYSCALL_sched_getattr 381
#define __SPRT_SYSCALL_renameat2 382
#define __SPRT_SYSCALL_seccomp 383
#define __SPRT_SYSCALL_getrandom 384
#define __SPRT_SYSCALL_memfd_create 385
#define __SPRT_SYSCALL_bpf 386
#define __SPRT_SYSCALL_execveat 387
#define __SPRT_SYSCALL_userfaultfd 388
#define __SPRT_SYSCALL_membarrier 389
#define __SPRT_SYSCALL_mlock2 390
#define __SPRT_SYSCALL_copy_file_range 391
#define __SPRT_SYSCALL_preadv2 392
#define __SPRT_SYSCALL_pwritev2 393
#define __SPRT_SYSCALL_pkey_mprotect 394
#define __SPRT_SYSCALL_pkey_alloc 395
#define __SPRT_SYSCALL_pkey_free 396
#define __SPRT_SYSCALL_statx 397
#define __SPRT_SYSCALL_rseq 398
#define __SPRT_SYSCALL_io_pgetevents 399
#define __SPRT_SYSCALL_migrate_pages 400
#define __SPRT_SYSCALL_kexec_file_load 401
#define __SPRT_SYSCALL_clock_gettime64 403
#define __SPRT_SYSCALL_clock_settime64 404
#define __SPRT_SYSCALL_clock_adjtime64 405
#define __SPRT_SYSCALL_clock_getres_time64 406
#define __SPRT_SYSCALL_clock_nanosleep_time64 407
#define __SPRT_SYSCALL_timer_gettime64 408
#define __SPRT_SYSCALL_timer_settime64 409
#define __SPRT_SYSCALL_timerfd_gettime64 410
#define __SPRT_SYSCALL_timerfd_settime64 411
#define __SPRT_SYSCALL_utimensat_time64 412
#define __SPRT_SYSCALL_pselect6_time64 413
#define __SPRT_SYSCALL_ppoll_time64 414
#define __SPRT_SYSCALL_io_pgetevents_time64 416
#define __SPRT_SYSCALL_recvmmsg_time64 417
#define __SPRT_SYSCALL_mq_timedsend_time64 418
#define __SPRT_SYSCALL_mq_timedreceive_time64 419
#define __SPRT_SYSCALL_semtimedop_time64 420
#define __SPRT_SYSCALL_rt_sigtimedwait_time64 421
#define __SPRT_SYSCALL_futex_time64 422
#define __SPRT_SYSCALL_sched_rr_get_interval_time64 423
#define __SPRT_SYSCALL_pidfd_send_signal 424
#define __SPRT_SYSCALL_io_uring_setup 425
#define __SPRT_SYSCALL_io_uring_enter 426
#define __SPRT_SYSCALL_io_uring_register 427
#define __SPRT_SYSCALL_open_tree 428
#define __SPRT_SYSCALL_move_mount 429
#define __SPRT_SYSCALL_fsopen 430
#define __SPRT_SYSCALL_fsconfig 431
#define __SPRT_SYSCALL_fsmount 432
#define __SPRT_SYSCALL_fspick 433
#define __SPRT_SYSCALL_pidfd_open 434
#define __SPRT_SYSCALL_clone3 435
#define __SPRT_SYSCALL_close_range 436
#define __SPRT_SYSCALL_openat2 437
#define __SPRT_SYSCALL_pidfd_getfd 438
#define __SPRT_SYSCALL_faccessat2 439
#define __SPRT_SYSCALL_process_madvise 440
#define __SPRT_SYSCALL_epoll_pwait2 441
#define __SPRT_SYSCALL_mount_setattr 442
#define __SPRT_SYSCALL_quotactl_fd 443
#define __SPRT_SYSCALL_landlock_create_ruleset 444
#define __SPRT_SYSCALL_landlock_add_rule 445
#define __SPRT_SYSCALL_landlock_restrict_self 446
#define __SPRT_SYSCALL_process_mrelease 448
#define __SPRT_SYSCALL_futex_waitv 449
#define __SPRT_SYSCALL_set_mempolicy_home_node 450
#define __SPRT_SYSCALL_cachestat 451
#define __SPRT_SYSCALL_fchmodat2 452
#define __SPRT_SYSCALL_map_shadow_stack 453
#define __SPRT_SYSCALL_futex_wake 454
#define __SPRT_SYSCALL_futex_wait 455
#define __SPRT_SYSCALL_futex_requeue 456
#define __SPRT_SYSCALL_statmount 457
#define __SPRT_SYSCALL_listmount 458
#define __SPRT_SYSCALL_lsm_get_self_attr 459
#define __SPRT_SYSCALL_lsm_set_self_attr 460
#define __SPRT_SYSCALL_lsm_list_modules 461
#define __SPRT_SYSCALL_mseal 462
#define __SPRT_SYSCALL_setxattrat 463
#define __SPRT_SYSCALL_getxattrat 464
#define __SPRT_SYSCALL_listxattrat 465
#define __SPRT_SYSCALL_removexattrat 466
#define __SPRT_SYSCALL_open_tree_attr 467
#define __SPRT_SYSCALL_file_getattr 468
#define __SPRT_SYSCALL_file_setattr 469
