#define __SPRT_SYSCALL_io_setup 0
#define __SPRT_SYSCALL_io_destroy 1
#define __SPRT_SYSCALL_io_submit 2
#define __SPRT_SYSCALL_io_cancel 3
#define __SPRT_SYSCALL_io_getevents 4
#define __SPRT_SYSCALL_setxattr 5
#define __SPRT_SYSCALL_lsetxattr 6
#define __SPRT_SYSCALL_fsetxattr 7
#define __SPRT_SYSCALL_getxattr 8
#define __SPRT_SYSCALL_lgetxattr 9
#define __SPRT_SYSCALL_fgetxattr 10
#define __SPRT_SYSCALL_listxattr 11
#define __SPRT_SYSCALL_llistxattr 12
#define __SPRT_SYSCALL_flistxattr 13
#define __SPRT_SYSCALL_removexattr 14
#define __SPRT_SYSCALL_lremovexattr 15
#define __SPRT_SYSCALL_fremovexattr 16
#define __SPRT_SYSCALL_getcwd 17
#define __SPRT_SYSCALL_lookup_dcookie 18
#define __SPRT_SYSCALL_eventfd2 19
#define __SPRT_SYSCALL_epoll_create1 20
#define __SPRT_SYSCALL_epoll_ctl 21
#define __SPRT_SYSCALL_epoll_pwait 22
#define __SPRT_SYSCALL_dup 23
#define __SPRT_SYSCALL_dup3 24
#define __SPRT_SYSCALL_fcntl 25
#define __SPRT_SYSCALL_inotify_init1 26
#define __SPRT_SYSCALL_inotify_add_watch 27
#define __SPRT_SYSCALL_inotify_rm_watch 28
#define __SPRT_SYSCALL_ioctl 29
#define __SPRT_SYSCALL_ioprio_set 30
#define __SPRT_SYSCALL_ioprio_get 31
#define __SPRT_SYSCALL_flock 32
#define __SPRT_SYSCALL_mknodat 33
#define __SPRT_SYSCALL_mkdirat 34
#define __SPRT_SYSCALL_unlinkat 35
#define __SPRT_SYSCALL_symlinkat 36
#define __SPRT_SYSCALL_linkat 37
#define __SPRT_SYSCALL_renameat 38
#define __SPRT_SYSCALL_umount2 39
#define __SPRT_SYSCALL_mount 40
#define __SPRT_SYSCALL_pivot_root 41
#define __SPRT_SYSCALL_nfsservctl 42
#define __SPRT_SYSCALL_statfs 43
#define __SPRT_SYSCALL_fstatfs 44
#define __SPRT_SYSCALL_truncate 45
#define __SPRT_SYSCALL_ftruncate 46
#define __SPRT_SYSCALL_fallocate 47
#define __SPRT_SYSCALL_faccessat 48
#define __SPRT_SYSCALL_chdir 49
#define __SPRT_SYSCALL_fchdir 50
#define __SPRT_SYSCALL_chroot 51
#define __SPRT_SYSCALL_fchmod 52
#define __SPRT_SYSCALL_fchmodat 53
#define __SPRT_SYSCALL_fchownat 54
#define __SPRT_SYSCALL_fchown 55
#define __SPRT_SYSCALL_openat 56
#define __SPRT_SYSCALL_close 57
#define __SPRT_SYSCALL_vhangup 58
#define __SPRT_SYSCALL_pipe2 59
#define __SPRT_SYSCALL_quotactl 60
#define __SPRT_SYSCALL_getdents64 61
#define __SPRT_SYSCALL_lseek 62
#define __SPRT_SYSCALL_read 63
#define __SPRT_SYSCALL_write 64
#define __SPRT_SYSCALL_readv 65
#define __SPRT_SYSCALL_writev 66
#define __SPRT_SYSCALL_pread64 67
#define __SPRT_SYSCALL_pwrite64 68
#define __SPRT_SYSCALL_preadv 69
#define __SPRT_SYSCALL_pwritev 70
#define __SPRT_SYSCALL_sendfile 71
#define __SPRT_SYSCALL_pselect6 72
#define __SPRT_SYSCALL_ppoll 73
#define __SPRT_SYSCALL_signalfd4 74
#define __SPRT_SYSCALL_vmsplice 75
#define __SPRT_SYSCALL_splice 76
#define __SPRT_SYSCALL_tee 77
#define __SPRT_SYSCALL_readlinkat 78
#define __SPRT_SYSCALL_newfstatat 79
#define __SPRT_SYSCALL_fstat 80
#define __SPRT_SYSCALL_sync 81
#define __SPRT_SYSCALL_fsync 82
#define __SPRT_SYSCALL_fdatasync 83
#define __SPRT_SYSCALL_sync_file_range 84
#define __SPRT_SYSCALL_timerfd_create 85
#define __SPRT_SYSCALL_timerfd_settime 86
#define __SPRT_SYSCALL_timerfd_gettime 87
#define __SPRT_SYSCALL_utimensat 88
#define __SPRT_SYSCALL_acct 89
#define __SPRT_SYSCALL_capget 90
#define __SPRT_SYSCALL_capset 91
#define __SPRT_SYSCALL_personality 92
#define __SPRT_SYSCALL_exit 93
#define __SPRT_SYSCALL_exit_group 94
#define __SPRT_SYSCALL_waitid 95
#define __SPRT_SYSCALL_set_tid_address 96
#define __SPRT_SYSCALL_unshare 97
#define __SPRT_SYSCALL_futex 98
#define __SPRT_SYSCALL_set_robust_list 99
#define __SPRT_SYSCALL_get_robust_list 100
#define __SPRT_SYSCALL_nanosleep 101
#define __SPRT_SYSCALL_getitimer 102
#define __SPRT_SYSCALL_setitimer 103
#define __SPRT_SYSCALL_kexec_load 104
#define __SPRT_SYSCALL_init_module 105
#define __SPRT_SYSCALL_delete_module 106
#define __SPRT_SYSCALL_timer_create 107
#define __SPRT_SYSCALL_timer_gettime 108
#define __SPRT_SYSCALL_timer_getoverrun 109
#define __SPRT_SYSCALL_timer_settime 110
#define __SPRT_SYSCALL_timer_delete 111
#define __SPRT_SYSCALL_clock_settime 112
#define __SPRT_SYSCALL_clock_gettime 113
#define __SPRT_SYSCALL_clock_getres 114
#define __SPRT_SYSCALL_clock_nanosleep 115
#define __SPRT_SYSCALL_syslog 116
#define __SPRT_SYSCALL_ptrace 117
#define __SPRT_SYSCALL_sched_setparam 118
#define __SPRT_SYSCALL_sched_setscheduler 119
#define __SPRT_SYSCALL_sched_getscheduler 120
#define __SPRT_SYSCALL_sched_getparam 121
#define __SPRT_SYSCALL_sched_setaffinity 122
#define __SPRT_SYSCALL_sched_getaffinity 123
#define __SPRT_SYSCALL_sched_yield 124
#define __SPRT_SYSCALL_sched_get_priority_max 125
#define __SPRT_SYSCALL_sched_get_priority_min 126
#define __SPRT_SYSCALL_sched_rr_get_interval 127
#define __SPRT_SYSCALL_restart_syscall 128
#define __SPRT_SYSCALL_kill 129
#define __SPRT_SYSCALL_tkill 130
#define __SPRT_SYSCALL_tgkill 131
#define __SPRT_SYSCALL_sigaltstack 132
#define __SPRT_SYSCALL_rt_sigsuspend 133
#define __SPRT_SYSCALL_rt_sigaction 134
#define __SPRT_SYSCALL_rt_sigprocmask 135
#define __SPRT_SYSCALL_rt_sigpending 136
#define __SPRT_SYSCALL_rt_sigtimedwait 137
#define __SPRT_SYSCALL_rt_sigqueueinfo 138
#define __SPRT_SYSCALL_rt_sigreturn 139
#define __SPRT_SYSCALL_setpriority 140
#define __SPRT_SYSCALL_getpriority 141
#define __SPRT_SYSCALL_reboot 142
#define __SPRT_SYSCALL_setregid 143
#define __SPRT_SYSCALL_setgid 144
#define __SPRT_SYSCALL_setreuid 145
#define __SPRT_SYSCALL_setuid 146
#define __SPRT_SYSCALL_setresuid 147
#define __SPRT_SYSCALL_getresuid 148
#define __SPRT_SYSCALL_setresgid 149
#define __SPRT_SYSCALL_getresgid 150
#define __SPRT_SYSCALL_setfsuid 151
#define __SPRT_SYSCALL_setfsgid 152
#define __SPRT_SYSCALL_times 153
#define __SPRT_SYSCALL_setpgid 154
#define __SPRT_SYSCALL_getpgid 155
#define __SPRT_SYSCALL_getsid 156
#define __SPRT_SYSCALL_setsid 157
#define __SPRT_SYSCALL_getgroups 158
#define __SPRT_SYSCALL_setgroups 159
#define __SPRT_SYSCALL_uname 160
#define __SPRT_SYSCALL_sethostname 161
#define __SPRT_SYSCALL_setdomainname 162
#define __SPRT_SYSCALL_getrlimit 163
#define __SPRT_SYSCALL_setrlimit 164
#define __SPRT_SYSCALL_getrusage 165
#define __SPRT_SYSCALL_umask 166
#define __SPRT_SYSCALL_prctl 167
#define __SPRT_SYSCALL_getcpu 168
#define __SPRT_SYSCALL_gettimeofday 169
#define __SPRT_SYSCALL_settimeofday 170
#define __SPRT_SYSCALL_adjtimex 171
#define __SPRT_SYSCALL_getpid 172
#define __SPRT_SYSCALL_getppid 173
#define __SPRT_SYSCALL_getuid 174
#define __SPRT_SYSCALL_geteuid 175
#define __SPRT_SYSCALL_getgid 176
#define __SPRT_SYSCALL_getegid 177
#define __SPRT_SYSCALL_gettid 178
#define __SPRT_SYSCALL_sysinfo 179
#define __SPRT_SYSCALL_mq_open 180
#define __SPRT_SYSCALL_mq_unlink 181
#define __SPRT_SYSCALL_mq_timedsend 182
#define __SPRT_SYSCALL_mq_timedreceive 183
#define __SPRT_SYSCALL_mq_notify 184
#define __SPRT_SYSCALL_mq_getsetattr 185
#define __SPRT_SYSCALL_msgget 186
#define __SPRT_SYSCALL_msgctl 187
#define __SPRT_SYSCALL_msgrcv 188
#define __SPRT_SYSCALL_msgsnd 189
#define __SPRT_SYSCALL_semget 190
#define __SPRT_SYSCALL_semctl 191
#define __SPRT_SYSCALL_semtimedop 192
#define __SPRT_SYSCALL_semop 193
#define __SPRT_SYSCALL_shmget 194
#define __SPRT_SYSCALL_shmctl 195
#define __SPRT_SYSCALL_shmat 196
#define __SPRT_SYSCALL_shmdt 197
#define __SPRT_SYSCALL_socket 198
#define __SPRT_SYSCALL_socketpair 199
#define __SPRT_SYSCALL_bind 200
#define __SPRT_SYSCALL_listen 201
#define __SPRT_SYSCALL_accept 202
#define __SPRT_SYSCALL_connect 203
#define __SPRT_SYSCALL_getsockname 204
#define __SPRT_SYSCALL_getpeername 205
#define __SPRT_SYSCALL_sendto 206
#define __SPRT_SYSCALL_recvfrom 207
#define __SPRT_SYSCALL_setsockopt 208
#define __SPRT_SYSCALL_getsockopt 209
#define __SPRT_SYSCALL_shutdown 210
#define __SPRT_SYSCALL_sendmsg 211
#define __SPRT_SYSCALL_recvmsg 212
#define __SPRT_SYSCALL_readahead 213
#define __SPRT_SYSCALL_brk 214
#define __SPRT_SYSCALL_munmap 215
#define __SPRT_SYSCALL_mremap 216
#define __SPRT_SYSCALL_add_key 217
#define __SPRT_SYSCALL_request_key 218
#define __SPRT_SYSCALL_keyctl 219
#define __SPRT_SYSCALL_clone 220
#define __SPRT_SYSCALL_execve 221
#define __SPRT_SYSCALL_mmap 222
#define __SPRT_SYSCALL_fadvise64 223
#define __SPRT_SYSCALL_swapon 224
#define __SPRT_SYSCALL_swapoff 225
#define __SPRT_SYSCALL_mprotect 226
#define __SPRT_SYSCALL_msync 227
#define __SPRT_SYSCALL_mlock 228
#define __SPRT_SYSCALL_munlock 229
#define __SPRT_SYSCALL_mlockall 230
#define __SPRT_SYSCALL_munlockall 231
#define __SPRT_SYSCALL_mincore 232
#define __SPRT_SYSCALL_madvise 233
#define __SPRT_SYSCALL_remap_file_pages 234
#define __SPRT_SYSCALL_mbind 235
#define __SPRT_SYSCALL_get_mempolicy 236
#define __SPRT_SYSCALL_set_mempolicy 237
#define __SPRT_SYSCALL_migrate_pages 238
#define __SPRT_SYSCALL_move_pages 239
#define __SPRT_SYSCALL_rt_tgsigqueueinfo 240
#define __SPRT_SYSCALL_perf_event_open 241
#define __SPRT_SYSCALL_accept4 242
#define __SPRT_SYSCALL_recvmmsg 243
#define __SPRT_SYSCALL_wait4 260
#define __SPRT_SYSCALL_prlimit64 261
#define __SPRT_SYSCALL_fanotify_init 262
#define __SPRT_SYSCALL_fanotify_mark 263
#define __SPRT_SYSCALL_name_to_handle_at 264
#define __SPRT_SYSCALL_open_by_handle_at 265
#define __SPRT_SYSCALL_clock_adjtime 266
#define __SPRT_SYSCALL_syncfs 267
#define __SPRT_SYSCALL_setns 268
#define __SPRT_SYSCALL_sendmmsg 269
#define __SPRT_SYSCALL_process_vm_readv 270
#define __SPRT_SYSCALL_process_vm_writev 271
#define __SPRT_SYSCALL_kcmp 272
#define __SPRT_SYSCALL_finit_module 273
#define __SPRT_SYSCALL_sched_setattr 274
#define __SPRT_SYSCALL_sched_getattr 275
#define __SPRT_SYSCALL_renameat2 276
#define __SPRT_SYSCALL_seccomp 277
#define __SPRT_SYSCALL_getrandom 278
#define __SPRT_SYSCALL_memfd_create 279
#define __SPRT_SYSCALL_bpf 280
#define __SPRT_SYSCALL_execveat 281
#define __SPRT_SYSCALL_userfaultfd 282
#define __SPRT_SYSCALL_membarrier 283
#define __SPRT_SYSCALL_mlock2 284
#define __SPRT_SYSCALL_copy_file_range 285
#define __SPRT_SYSCALL_preadv2 286
#define __SPRT_SYSCALL_pwritev2 287
#define __SPRT_SYSCALL_pkey_mprotect 288
#define __SPRT_SYSCALL_pkey_alloc 289
#define __SPRT_SYSCALL_pkey_free 290
#define __SPRT_SYSCALL_statx 291
#define __SPRT_SYSCALL_io_pgetevents 292
#define __SPRT_SYSCALL_rseq 293
#define __SPRT_SYSCALL_kexec_file_load 294
#define __SPRT_SYSCALL_pidfd_send_signal 424
#define __SPRT_SYSCALL_io_uring_setup 425
#define __SPRT_SYSCALL_io_uring_enter 426
#define __SPRT_SYSCALL_io_uring_register 427
#define __SPRT_SYSCALL_open_tree 428
#define __SPRT_SYSCALL_move_mount 429
#define __SPRT_SYSCALL_fsopen 430
#define __SPRT_SYSCALL_fsconfig 431
#define __SPRT_SYSCALL_fsmount 432
#define __SPRT_SYSCALL_fspick 433
#define __SPRT_SYSCALL_pidfd_open 434
#define __SPRT_SYSCALL_clone3 435
#define __SPRT_SYSCALL_close_range 436
#define __SPRT_SYSCALL_openat2 437
#define __SPRT_SYSCALL_pidfd_getfd 438
#define __SPRT_SYSCALL_faccessat2 439
#define __SPRT_SYSCALL_process_madvise 440
#define __SPRT_SYSCALL_epoll_pwait2 441
#define __SPRT_SYSCALL_mount_setattr 442
#define __SPRT_SYSCALL_quotactl_fd 443
#define __SPRT_SYSCALL_landlock_create_ruleset 444
#define __SPRT_SYSCALL_landlock_add_rule 445
#define __SPRT_SYSCALL_landlock_restrict_self 446
#define __SPRT_SYSCALL_memfd_secret 447
#define __SPRT_SYSCALL_process_mrelease 448
#define __SPRT_SYSCALL_futex_waitv 449
#define __SPRT_SYSCALL_set_mempolicy_home_node 450
#define __SPRT_SYSCALL_cachestat 451
#define __SPRT_SYSCALL_fchmodat2 452
#define __SPRT_SYSCALL_map_shadow_stack 453
#define __SPRT_SYSCALL_futex_wake 454
#define __SPRT_SYSCALL_futex_wait 455
#define __SPRT_SYSCALL_futex_requeue 456
#define __SPRT_SYSCALL_statmount 457
#define __SPRT_SYSCALL_listmount 458
#define __SPRT_SYSCALL_lsm_get_self_attr 459
#define __SPRT_SYSCALL_lsm_set_self_attr 460
#define __SPRT_SYSCALL_lsm_list_modules 461
#define __SPRT_SYSCALL_mseal 462
#define __SPRT_SYSCALL_setxattrat 463
#define __SPRT_SYSCALL_getxattrat 464
#define __SPRT_SYSCALL_listxattrat 465
#define __SPRT_SYSCALL_removexattrat 466
#define __SPRT_SYSCALL_open_tree_attr 467
#define __SPRT_SYSCALL_file_getattr 468
#define __SPRT_SYSCALL_file_setattr 469
